/* automatically generated by rust-bindgen 0.72.1 */

pub type wchar_t = ::core::ffi::c_int;
pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
pub type intmax_t = ::core::ffi::c_long;
pub type uintmax_t = ::core::ffi::c_ulong;
pub type avifBool = ::core::ffi::c_int;
pub type avifPlanesFlags = u32;
pub type avifHeaderFormatFlags = ::core::ffi::c_int;
pub type avifTransformFlags = u32;
pub type avifCodecFlags = u32;
pub type avifIODestroyFunc = ::core::option::Option<unsafe extern "C" fn(io: *mut avifIO)>;
pub type avifIOReadFunc = ::core::option::Option<
    unsafe extern "C" fn(
        io: *mut avifIO,
        readFlags: u32,
        offset: u64,
        size: usize,
        out: *mut avifROData,
    ) -> avifResult,
>;
pub type avifIOWriteFunc = ::core::option::Option<
    unsafe extern "C" fn(
        io: *mut avifIO,
        writeFlags: u32,
        offset: u64,
        data: *const u8,
        size: usize,
    ) -> avifResult,
>;
pub type avifStrictFlags = u32;
pub type avifImageContentTypeFlags = u32;
pub type avifAddImageFlags = u32;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug)]
pub struct max_align_t {
    pub __clang_max_align_nonce1: ::core::ffi::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __clang_max_align_nonce2: u128,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifPlanesFlag(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChannelIndex(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifResult(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifHeaderFormat(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifROData {
    pub data: *const u8,
    pub size: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifRWData {
    pub data: *mut u8,
    pub size: usize,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifPixelFormat(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifPixelFormatInfo {
    pub monochrome: avifBool,
    pub chromaShiftX: ::core::ffi::c_int,
    pub chromaShiftY: ::core::ffi::c_int,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChromaSamplePosition(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifRange(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifColorPrimaries(pub u16);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifTransferCharacteristics(pub u16);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifMatrixCoefficients(pub u16);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifDiagnostics {
    pub error: [::core::ffi::c_char; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifFraction {
    pub n: i32,
    pub d: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifSignedFraction {
    pub n: i32,
    pub d: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifUnsignedFraction {
    pub n: u32,
    pub d: u32,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifTransformFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifPixelAspectRatioBox {
    pub hSpacing: u32,
    pub vSpacing: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifCleanApertureBox {
    pub widthN: u32,
    pub widthD: u32,
    pub heightN: u32,
    pub heightD: u32,
    pub horizOffN: u32,
    pub horizOffD: u32,
    pub vertOffN: u32,
    pub vertOffD: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifImageRotation {
    pub angle: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifImageMirror {
    pub axis: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifCropRect {
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifContentLightLevelInformationBox {
    pub maxCLL: u16,
    pub maxPALL: u16,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifGainMap {
    pub image: *mut avifImage,
    pub gainMapMin: [avifSignedFraction; 3usize],
    pub gainMapMax: [avifSignedFraction; 3usize],
    pub gainMapGamma: [avifUnsignedFraction; 3usize],
    pub baseOffset: [avifSignedFraction; 3usize],
    pub alternateOffset: [avifSignedFraction; 3usize],
    pub baseHdrHeadroom: avifUnsignedFraction,
    pub alternateHdrHeadroom: avifUnsignedFraction,
    pub useBaseColorSpace: avifBool,
    pub altICC: avifRWData,
    pub altColorPrimaries: avifColorPrimaries,
    pub altTransferCharacteristics: avifTransferCharacteristics,
    pub altMatrixCoefficients: avifMatrixCoefficients,
    pub altYUVRange: avifRange,
    pub altDepth: u32,
    pub altPlaneCount: u32,
    pub altCLLI: avifContentLightLevelInformationBox,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifSampleTransformRecipe(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifImageItemProperty {
    pub boxtype: [u8; 4usize],
    pub usertype: [u8; 16usize],
    pub boxPayload: avifRWData,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifImage {
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub yuvFormat: avifPixelFormat,
    pub yuvRange: avifRange,
    pub yuvChromaSamplePosition: avifChromaSamplePosition,
    pub yuvPlanes: [*mut u8; 3usize],
    pub yuvRowBytes: [u32; 3usize],
    pub imageOwnsYUVPlanes: avifBool,
    pub alphaPlane: *mut u8,
    pub alphaRowBytes: u32,
    pub imageOwnsAlphaPlane: avifBool,
    pub alphaPremultiplied: avifBool,
    pub icc: avifRWData,
    pub colorPrimaries: avifColorPrimaries,
    pub transferCharacteristics: avifTransferCharacteristics,
    pub matrixCoefficients: avifMatrixCoefficients,
    pub clli: avifContentLightLevelInformationBox,
    pub transformFlags: avifTransformFlags,
    pub pasp: avifPixelAspectRatioBox,
    pub clap: avifCleanApertureBox,
    pub irot: avifImageRotation,
    pub imir: avifImageMirror,
    pub exif: avifRWData,
    pub xmp: avifRWData,
    pub properties: *mut avifImageItemProperty,
    pub numProperties: usize,
    pub gainMap: *mut avifGainMap,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifRGBFormat(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChromaUpsampling(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChromaDownsampling(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifRGBImage {
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub format: avifRGBFormat,
    pub chromaUpsampling: avifChromaUpsampling,
    pub chromaDownsampling: avifChromaDownsampling,
    pub avoidLibYUV: avifBool,
    pub ignoreAlpha: avifBool,
    pub alphaPremultiplied: avifBool,
    pub isFloat: avifBool,
    pub maxThreads: ::core::ffi::c_int,
    pub pixels: *mut u8,
    pub rowBytes: u32,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifCodecChoice(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifCodecFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifIO {
    pub destroy: avifIODestroyFunc,
    pub read: avifIOReadFunc,
    pub write: avifIOWriteFunc,
    pub sizeHint: u64,
    pub persistent: avifBool,
    pub data: *mut ::core::ffi::c_void,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifStrictFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifIOStats {
    pub colorOBUSize: usize,
    pub alphaOBUSize: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifDecoderData {
    _unused: [u8; 0],
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifDecoderSource(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, PartialEq)]
pub struct avifImageTiming {
    pub timescale: u64,
    pub pts: f64,
    pub ptsInTimescales: u64,
    pub duration: f64,
    pub durationInTimescales: u64,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifProgressiveState(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifImageContentTypeFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifDecoder {
    pub codecChoice: avifCodecChoice,
    pub maxThreads: ::core::ffi::c_int,
    pub requestedSource: avifDecoderSource,
    pub allowProgressive: avifBool,
    pub allowIncremental: avifBool,
    pub ignoreExif: avifBool,
    pub ignoreXMP: avifBool,
    pub imageSizeLimit: u32,
    pub imageDimensionLimit: u32,
    pub imageCountLimit: u32,
    pub strictFlags: avifStrictFlags,
    pub image: *mut avifImage,
    pub imageIndex: ::core::ffi::c_int,
    pub imageCount: ::core::ffi::c_int,
    pub progressiveState: avifProgressiveState,
    pub imageTiming: avifImageTiming,
    pub timescale: u64,
    pub duration: f64,
    pub durationInTimescales: u64,
    pub repetitionCount: ::core::ffi::c_int,
    pub alphaPresent: avifBool,
    pub ioStats: avifIOStats,
    pub diag: avifDiagnostics,
    pub io: *mut avifIO,
    pub data: *mut avifDecoderData,
    pub imageSequenceTrackPresent: avifBool,
    pub imageContentToDecode: avifImageContentTypeFlags,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifExtent {
    pub offset: u64,
    pub size: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifEncoderData {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct avifCodecSpecificOptions {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifScalingMode {
    pub horizontal: avifFraction,
    pub vertical: avifFraction,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifEncoder {
    pub codecChoice: avifCodecChoice,
    pub maxThreads: ::core::ffi::c_int,
    pub speed: ::core::ffi::c_int,
    pub keyframeInterval: ::core::ffi::c_int,
    pub timescale: u64,
    pub repetitionCount: ::core::ffi::c_int,
    pub extraLayerCount: u32,
    pub quality: ::core::ffi::c_int,
    pub qualityAlpha: ::core::ffi::c_int,
    pub minQuantizer: ::core::ffi::c_int,
    pub maxQuantizer: ::core::ffi::c_int,
    pub minQuantizerAlpha: ::core::ffi::c_int,
    pub maxQuantizerAlpha: ::core::ffi::c_int,
    pub tileRowsLog2: ::core::ffi::c_int,
    pub tileColsLog2: ::core::ffi::c_int,
    pub autoTiling: avifBool,
    pub scalingMode: avifScalingMode,
    pub ioStats: avifIOStats,
    pub diag: avifDiagnostics,
    pub data: *mut avifEncoderData,
    pub csOptions: *mut avifCodecSpecificOptions,
    pub headerFormat: avifHeaderFormatFlags,
    pub qualityGainMap: ::core::ffi::c_int,
    pub creationTime: u64,
    pub modificationTime: u64,
    pub sampleTransformRecipe: avifSampleTransformRecipe,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifAddImageFlag(pub ::core::ffi::c_uint);
pub const AVIF_VERSION_MAJOR: u32 = 1;
pub const AVIF_VERSION_MINOR: u32 = 4;
pub const AVIF_VERSION_PATCH: u32 = 2;
pub const AVIF_VERSION_DEVEL: u32 = 0;
pub const AVIF_VERSION: u32 = 1040200;
pub const AVIF_TRUE: u32 = 1;
pub const AVIF_FALSE: u32 = 0;
pub const AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE: u32 = 256;
pub const AVIF_DEFAULT_IMAGE_SIZE_LIMIT: u32 = 268435456;
pub const AVIF_DEFAULT_IMAGE_DIMENSION_LIMIT: u32 = 32768;
pub const AVIF_DEFAULT_IMAGE_COUNT_LIMIT: u32 = 2592000;
pub const AVIF_QUALITY_DEFAULT: i32 = -1;
pub const AVIF_QUALITY_WORST: u32 = 0;
pub const AVIF_QUALITY_BEST: u32 = 100;
pub const AVIF_QUALITY_LOSSLESS: u32 = 100;
pub const AVIF_QUANTIZER_LOSSLESS: u32 = 0;
pub const AVIF_QUANTIZER_BEST_QUALITY: u32 = 0;
pub const AVIF_QUANTIZER_WORST_QUALITY: u32 = 63;
pub const AVIF_PLANE_COUNT_YUV: u32 = 3;
pub const AVIF_SPEED_DEFAULT: i32 = -1;
pub const AVIF_SPEED_SLOWEST: u32 = 0;
pub const AVIF_SPEED_FASTEST: u32 = 10;
pub const AVIF_REPETITION_COUNT_INFINITE: i32 = -1;
pub const AVIF_REPETITION_COUNT_UNKNOWN: i32 = -2;
pub const AVIF_MAX_AV1_LAYER_COUNT: u32 = 4;
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of max_align_t"][::core::mem::size_of::<max_align_t>() - 32usize];
    ["Alignment of max_align_t"][::core::mem::align_of::<max_align_t>() - 16usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce1"]
        [::core::mem::offset_of!(max_align_t, __clang_max_align_nonce1) - 0usize];
    ["Offset of field: max_align_t::__clang_max_align_nonce2"]
        [::core::mem::offset_of!(max_align_t, __clang_max_align_nonce2) - 16usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifROData"][::core::mem::size_of::<avifROData>() - 16usize];
    ["Alignment of avifROData"][::core::mem::align_of::<avifROData>() - 8usize];
    ["Offset of field: avifROData::data"][::core::mem::offset_of!(avifROData, data) - 0usize];
    ["Offset of field: avifROData::size"][::core::mem::offset_of!(avifROData, size) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifRWData"][::core::mem::size_of::<avifRWData>() - 16usize];
    ["Alignment of avifRWData"][::core::mem::align_of::<avifRWData>() - 8usize];
    ["Offset of field: avifRWData::data"][::core::mem::offset_of!(avifRWData, data) - 0usize];
    ["Offset of field: avifRWData::size"][::core::mem::offset_of!(avifRWData, size) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifPixelFormatInfo"][::core::mem::size_of::<avifPixelFormatInfo>() - 12usize];
    ["Alignment of avifPixelFormatInfo"][::core::mem::align_of::<avifPixelFormatInfo>() - 4usize];
    ["Offset of field: avifPixelFormatInfo::monochrome"]
        [::core::mem::offset_of!(avifPixelFormatInfo, monochrome) - 0usize];
    ["Offset of field: avifPixelFormatInfo::chromaShiftX"]
        [::core::mem::offset_of!(avifPixelFormatInfo, chromaShiftX) - 4usize];
    ["Offset of field: avifPixelFormatInfo::chromaShiftY"]
        [::core::mem::offset_of!(avifPixelFormatInfo, chromaShiftY) - 8usize];
};
pub const AVIF_COLOR_PRIMARIES_UNKNOWN: avifColorPrimaries = avifColorPrimaries(0);
pub const AVIF_COLOR_PRIMARIES_BT709: avifColorPrimaries = avifColorPrimaries(1);
pub const AVIF_COLOR_PRIMARIES_SRGB: avifColorPrimaries = avifColorPrimaries(1);
pub const AVIF_COLOR_PRIMARIES_IEC61966_2_4: avifColorPrimaries = avifColorPrimaries(1);
pub const AVIF_COLOR_PRIMARIES_UNSPECIFIED: avifColorPrimaries = avifColorPrimaries(2);
pub const AVIF_COLOR_PRIMARIES_BT470M: avifColorPrimaries = avifColorPrimaries(4);
pub const AVIF_COLOR_PRIMARIES_BT470BG: avifColorPrimaries = avifColorPrimaries(5);
pub const AVIF_COLOR_PRIMARIES_BT601: avifColorPrimaries = avifColorPrimaries(6);
pub const AVIF_COLOR_PRIMARIES_SMPTE240: avifColorPrimaries = avifColorPrimaries(7);
pub const AVIF_COLOR_PRIMARIES_GENERIC_FILM: avifColorPrimaries = avifColorPrimaries(8);
pub const AVIF_COLOR_PRIMARIES_BT2020: avifColorPrimaries = avifColorPrimaries(9);
pub const AVIF_COLOR_PRIMARIES_BT2100: avifColorPrimaries = avifColorPrimaries(9);
pub const AVIF_COLOR_PRIMARIES_XYZ: avifColorPrimaries = avifColorPrimaries(10);
pub const AVIF_COLOR_PRIMARIES_SMPTE431: avifColorPrimaries = avifColorPrimaries(11);
pub const AVIF_COLOR_PRIMARIES_SMPTE432: avifColorPrimaries = avifColorPrimaries(12);
pub const AVIF_COLOR_PRIMARIES_DCI_P3: avifColorPrimaries = avifColorPrimaries(12);
pub const AVIF_COLOR_PRIMARIES_EBU3213: avifColorPrimaries = avifColorPrimaries(22);
pub const AVIF_TRANSFER_CHARACTERISTICS_UNKNOWN: avifTransferCharacteristics =
    avifTransferCharacteristics(0);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT709: avifTransferCharacteristics =
    avifTransferCharacteristics(1);
pub const AVIF_TRANSFER_CHARACTERISTICS_UNSPECIFIED: avifTransferCharacteristics =
    avifTransferCharacteristics(2);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT470M: avifTransferCharacteristics =
    avifTransferCharacteristics(4);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT470BG: avifTransferCharacteristics =
    avifTransferCharacteristics(5);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT601: avifTransferCharacteristics =
    avifTransferCharacteristics(6);
pub const AVIF_TRANSFER_CHARACTERISTICS_SMPTE240: avifTransferCharacteristics =
    avifTransferCharacteristics(7);
pub const AVIF_TRANSFER_CHARACTERISTICS_LINEAR: avifTransferCharacteristics =
    avifTransferCharacteristics(8);
pub const AVIF_TRANSFER_CHARACTERISTICS_LOG100: avifTransferCharacteristics =
    avifTransferCharacteristics(9);
pub const AVIF_TRANSFER_CHARACTERISTICS_LOG100_SQRT10: avifTransferCharacteristics =
    avifTransferCharacteristics(10);
pub const AVIF_TRANSFER_CHARACTERISTICS_IEC61966: avifTransferCharacteristics =
    avifTransferCharacteristics(11);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT1361: avifTransferCharacteristics =
    avifTransferCharacteristics(12);
pub const AVIF_TRANSFER_CHARACTERISTICS_SRGB: avifTransferCharacteristics =
    avifTransferCharacteristics(13);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT2020_10BIT: avifTransferCharacteristics =
    avifTransferCharacteristics(14);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT2020_12BIT: avifTransferCharacteristics =
    avifTransferCharacteristics(15);
pub const AVIF_TRANSFER_CHARACTERISTICS_PQ: avifTransferCharacteristics =
    avifTransferCharacteristics(16);
pub const AVIF_TRANSFER_CHARACTERISTICS_SMPTE2084: avifTransferCharacteristics =
    avifTransferCharacteristics(16);
pub const AVIF_TRANSFER_CHARACTERISTICS_SMPTE428: avifTransferCharacteristics =
    avifTransferCharacteristics(17);
pub const AVIF_TRANSFER_CHARACTERISTICS_HLG: avifTransferCharacteristics =
    avifTransferCharacteristics(18);
pub const AVIF_MATRIX_COEFFICIENTS_IDENTITY: avifMatrixCoefficients = avifMatrixCoefficients(0);
pub const AVIF_MATRIX_COEFFICIENTS_BT709: avifMatrixCoefficients = avifMatrixCoefficients(1);
pub const AVIF_MATRIX_COEFFICIENTS_UNSPECIFIED: avifMatrixCoefficients = avifMatrixCoefficients(2);
pub const AVIF_MATRIX_COEFFICIENTS_FCC: avifMatrixCoefficients = avifMatrixCoefficients(4);
pub const AVIF_MATRIX_COEFFICIENTS_BT470BG: avifMatrixCoefficients = avifMatrixCoefficients(5);
pub const AVIF_MATRIX_COEFFICIENTS_BT601: avifMatrixCoefficients = avifMatrixCoefficients(6);
pub const AVIF_MATRIX_COEFFICIENTS_SMPTE240: avifMatrixCoefficients = avifMatrixCoefficients(7);
pub const AVIF_MATRIX_COEFFICIENTS_YCGCO: avifMatrixCoefficients = avifMatrixCoefficients(8);
pub const AVIF_MATRIX_COEFFICIENTS_BT2020_NCL: avifMatrixCoefficients = avifMatrixCoefficients(9);
pub const AVIF_MATRIX_COEFFICIENTS_BT2020_CL: avifMatrixCoefficients = avifMatrixCoefficients(10);
pub const AVIF_MATRIX_COEFFICIENTS_SMPTE2085: avifMatrixCoefficients = avifMatrixCoefficients(11);
pub const AVIF_MATRIX_COEFFICIENTS_CHROMA_DERIVED_NCL: avifMatrixCoefficients =
    avifMatrixCoefficients(12);
pub const AVIF_MATRIX_COEFFICIENTS_CHROMA_DERIVED_CL: avifMatrixCoefficients =
    avifMatrixCoefficients(13);
pub const AVIF_MATRIX_COEFFICIENTS_ICTCP: avifMatrixCoefficients = avifMatrixCoefficients(14);
pub const AVIF_MATRIX_COEFFICIENTS_YCGCO_RE: avifMatrixCoefficients = avifMatrixCoefficients(16);
pub const AVIF_MATRIX_COEFFICIENTS_YCGCO_RO: avifMatrixCoefficients = avifMatrixCoefficients(17);
pub const AVIF_MATRIX_COEFFICIENTS_LAST: avifMatrixCoefficients = avifMatrixCoefficients(18);
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifDiagnostics"][::core::mem::size_of::<avifDiagnostics>() - 256usize];
    ["Alignment of avifDiagnostics"][::core::mem::align_of::<avifDiagnostics>() - 1usize];
    ["Offset of field: avifDiagnostics::error"]
        [::core::mem::offset_of!(avifDiagnostics, error) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifFraction"][::core::mem::size_of::<avifFraction>() - 8usize];
    ["Alignment of avifFraction"][::core::mem::align_of::<avifFraction>() - 4usize];
    ["Offset of field: avifFraction::n"][::core::mem::offset_of!(avifFraction, n) - 0usize];
    ["Offset of field: avifFraction::d"][::core::mem::offset_of!(avifFraction, d) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifSignedFraction"][::core::mem::size_of::<avifSignedFraction>() - 8usize];
    ["Alignment of avifSignedFraction"][::core::mem::align_of::<avifSignedFraction>() - 4usize];
    ["Offset of field: avifSignedFraction::n"]
        [::core::mem::offset_of!(avifSignedFraction, n) - 0usize];
    ["Offset of field: avifSignedFraction::d"]
        [::core::mem::offset_of!(avifSignedFraction, d) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifUnsignedFraction"][::core::mem::size_of::<avifUnsignedFraction>() - 8usize];
    ["Alignment of avifUnsignedFraction"][::core::mem::align_of::<avifUnsignedFraction>() - 4usize];
    ["Offset of field: avifUnsignedFraction::n"]
        [::core::mem::offset_of!(avifUnsignedFraction, n) - 0usize];
    ["Offset of field: avifUnsignedFraction::d"]
        [::core::mem::offset_of!(avifUnsignedFraction, d) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifPixelAspectRatioBox"][::core::mem::size_of::<avifPixelAspectRatioBox>() - 8usize];
    ["Alignment of avifPixelAspectRatioBox"]
        [::core::mem::align_of::<avifPixelAspectRatioBox>() - 4usize];
    ["Offset of field: avifPixelAspectRatioBox::hSpacing"]
        [::core::mem::offset_of!(avifPixelAspectRatioBox, hSpacing) - 0usize];
    ["Offset of field: avifPixelAspectRatioBox::vSpacing"]
        [::core::mem::offset_of!(avifPixelAspectRatioBox, vSpacing) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifCleanApertureBox"][::core::mem::size_of::<avifCleanApertureBox>() - 32usize];
    ["Alignment of avifCleanApertureBox"][::core::mem::align_of::<avifCleanApertureBox>() - 4usize];
    ["Offset of field: avifCleanApertureBox::widthN"]
        [::core::mem::offset_of!(avifCleanApertureBox, widthN) - 0usize];
    ["Offset of field: avifCleanApertureBox::widthD"]
        [::core::mem::offset_of!(avifCleanApertureBox, widthD) - 4usize];
    ["Offset of field: avifCleanApertureBox::heightN"]
        [::core::mem::offset_of!(avifCleanApertureBox, heightN) - 8usize];
    ["Offset of field: avifCleanApertureBox::heightD"]
        [::core::mem::offset_of!(avifCleanApertureBox, heightD) - 12usize];
    ["Offset of field: avifCleanApertureBox::horizOffN"]
        [::core::mem::offset_of!(avifCleanApertureBox, horizOffN) - 16usize];
    ["Offset of field: avifCleanApertureBox::horizOffD"]
        [::core::mem::offset_of!(avifCleanApertureBox, horizOffD) - 20usize];
    ["Offset of field: avifCleanApertureBox::vertOffN"]
        [::core::mem::offset_of!(avifCleanApertureBox, vertOffN) - 24usize];
    ["Offset of field: avifCleanApertureBox::vertOffD"]
        [::core::mem::offset_of!(avifCleanApertureBox, vertOffD) - 28usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifImageRotation"][::core::mem::size_of::<avifImageRotation>() - 1usize];
    ["Alignment of avifImageRotation"][::core::mem::align_of::<avifImageRotation>() - 1usize];
    ["Offset of field: avifImageRotation::angle"]
        [::core::mem::offset_of!(avifImageRotation, angle) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifImageMirror"][::core::mem::size_of::<avifImageMirror>() - 1usize];
    ["Alignment of avifImageMirror"][::core::mem::align_of::<avifImageMirror>() - 1usize];
    ["Offset of field: avifImageMirror::axis"]
        [::core::mem::offset_of!(avifImageMirror, axis) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifCropRect"][::core::mem::size_of::<avifCropRect>() - 16usize];
    ["Alignment of avifCropRect"][::core::mem::align_of::<avifCropRect>() - 4usize];
    ["Offset of field: avifCropRect::x"][::core::mem::offset_of!(avifCropRect, x) - 0usize];
    ["Offset of field: avifCropRect::y"][::core::mem::offset_of!(avifCropRect, y) - 4usize];
    ["Offset of field: avifCropRect::width"][::core::mem::offset_of!(avifCropRect, width) - 8usize];
    ["Offset of field: avifCropRect::height"]
        [::core::mem::offset_of!(avifCropRect, height) - 12usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifContentLightLevelInformationBox"]
        [::core::mem::size_of::<avifContentLightLevelInformationBox>() - 4usize];
    ["Alignment of avifContentLightLevelInformationBox"]
        [::core::mem::align_of::<avifContentLightLevelInformationBox>() - 2usize];
    ["Offset of field: avifContentLightLevelInformationBox::maxCLL"]
        [::core::mem::offset_of!(avifContentLightLevelInformationBox, maxCLL) - 0usize];
    ["Offset of field: avifContentLightLevelInformationBox::maxPALL"]
        [::core::mem::offset_of!(avifContentLightLevelInformationBox, maxPALL) - 2usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifGainMap"][::core::mem::size_of::<avifGainMap>() - 192usize];
    ["Alignment of avifGainMap"][::core::mem::align_of::<avifGainMap>() - 8usize];
    ["Offset of field: avifGainMap::image"][::core::mem::offset_of!(avifGainMap, image) - 0usize];
    ["Offset of field: avifGainMap::gainMapMin"]
        [::core::mem::offset_of!(avifGainMap, gainMapMin) - 8usize];
    ["Offset of field: avifGainMap::gainMapMax"]
        [::core::mem::offset_of!(avifGainMap, gainMapMax) - 32usize];
    ["Offset of field: avifGainMap::gainMapGamma"]
        [::core::mem::offset_of!(avifGainMap, gainMapGamma) - 56usize];
    ["Offset of field: avifGainMap::baseOffset"]
        [::core::mem::offset_of!(avifGainMap, baseOffset) - 80usize];
    ["Offset of field: avifGainMap::alternateOffset"]
        [::core::mem::offset_of!(avifGainMap, alternateOffset) - 104usize];
    ["Offset of field: avifGainMap::baseHdrHeadroom"]
        [::core::mem::offset_of!(avifGainMap, baseHdrHeadroom) - 128usize];
    ["Offset of field: avifGainMap::alternateHdrHeadroom"]
        [::core::mem::offset_of!(avifGainMap, alternateHdrHeadroom) - 136usize];
    ["Offset of field: avifGainMap::useBaseColorSpace"]
        [::core::mem::offset_of!(avifGainMap, useBaseColorSpace) - 144usize];
    ["Offset of field: avifGainMap::altICC"]
        [::core::mem::offset_of!(avifGainMap, altICC) - 152usize];
    ["Offset of field: avifGainMap::altColorPrimaries"]
        [::core::mem::offset_of!(avifGainMap, altColorPrimaries) - 168usize];
    ["Offset of field: avifGainMap::altTransferCharacteristics"]
        [::core::mem::offset_of!(avifGainMap, altTransferCharacteristics) - 170usize];
    ["Offset of field: avifGainMap::altMatrixCoefficients"]
        [::core::mem::offset_of!(avifGainMap, altMatrixCoefficients) - 172usize];
    ["Offset of field: avifGainMap::altYUVRange"]
        [::core::mem::offset_of!(avifGainMap, altYUVRange) - 176usize];
    ["Offset of field: avifGainMap::altDepth"]
        [::core::mem::offset_of!(avifGainMap, altDepth) - 180usize];
    ["Offset of field: avifGainMap::altPlaneCount"]
        [::core::mem::offset_of!(avifGainMap, altPlaneCount) - 184usize];
    ["Offset of field: avifGainMap::altCLLI"]
        [::core::mem::offset_of!(avifGainMap, altCLLI) - 188usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifImageItemProperty"][::core::mem::size_of::<avifImageItemProperty>() - 40usize];
    ["Alignment of avifImageItemProperty"]
        [::core::mem::align_of::<avifImageItemProperty>() - 8usize];
    ["Offset of field: avifImageItemProperty::boxtype"]
        [::core::mem::offset_of!(avifImageItemProperty, boxtype) - 0usize];
    ["Offset of field: avifImageItemProperty::usertype"]
        [::core::mem::offset_of!(avifImageItemProperty, usertype) - 4usize];
    ["Offset of field: avifImageItemProperty::boxPayload"]
        [::core::mem::offset_of!(avifImageItemProperty, boxPayload) - 24usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifImage"][::core::mem::size_of::<avifImage>() - 224usize];
    ["Alignment of avifImage"][::core::mem::align_of::<avifImage>() - 8usize];
    ["Offset of field: avifImage::width"][::core::mem::offset_of!(avifImage, width) - 0usize];
    ["Offset of field: avifImage::height"][::core::mem::offset_of!(avifImage, height) - 4usize];
    ["Offset of field: avifImage::depth"][::core::mem::offset_of!(avifImage, depth) - 8usize];
    ["Offset of field: avifImage::yuvFormat"]
        [::core::mem::offset_of!(avifImage, yuvFormat) - 12usize];
    ["Offset of field: avifImage::yuvRange"]
        [::core::mem::offset_of!(avifImage, yuvRange) - 16usize];
    ["Offset of field: avifImage::yuvChromaSamplePosition"]
        [::core::mem::offset_of!(avifImage, yuvChromaSamplePosition) - 20usize];
    ["Offset of field: avifImage::yuvPlanes"]
        [::core::mem::offset_of!(avifImage, yuvPlanes) - 24usize];
    ["Offset of field: avifImage::yuvRowBytes"]
        [::core::mem::offset_of!(avifImage, yuvRowBytes) - 48usize];
    ["Offset of field: avifImage::imageOwnsYUVPlanes"]
        [::core::mem::offset_of!(avifImage, imageOwnsYUVPlanes) - 60usize];
    ["Offset of field: avifImage::alphaPlane"]
        [::core::mem::offset_of!(avifImage, alphaPlane) - 64usize];
    ["Offset of field: avifImage::alphaRowBytes"]
        [::core::mem::offset_of!(avifImage, alphaRowBytes) - 72usize];
    ["Offset of field: avifImage::imageOwnsAlphaPlane"]
        [::core::mem::offset_of!(avifImage, imageOwnsAlphaPlane) - 76usize];
    ["Offset of field: avifImage::alphaPremultiplied"]
        [::core::mem::offset_of!(avifImage, alphaPremultiplied) - 80usize];
    ["Offset of field: avifImage::icc"][::core::mem::offset_of!(avifImage, icc) - 88usize];
    ["Offset of field: avifImage::colorPrimaries"]
        [::core::mem::offset_of!(avifImage, colorPrimaries) - 104usize];
    ["Offset of field: avifImage::transferCharacteristics"]
        [::core::mem::offset_of!(avifImage, transferCharacteristics) - 106usize];
    ["Offset of field: avifImage::matrixCoefficients"]
        [::core::mem::offset_of!(avifImage, matrixCoefficients) - 108usize];
    ["Offset of field: avifImage::clli"][::core::mem::offset_of!(avifImage, clli) - 110usize];
    ["Offset of field: avifImage::transformFlags"]
        [::core::mem::offset_of!(avifImage, transformFlags) - 116usize];
    ["Offset of field: avifImage::pasp"][::core::mem::offset_of!(avifImage, pasp) - 120usize];
    ["Offset of field: avifImage::clap"][::core::mem::offset_of!(avifImage, clap) - 128usize];
    ["Offset of field: avifImage::irot"][::core::mem::offset_of!(avifImage, irot) - 160usize];
    ["Offset of field: avifImage::imir"][::core::mem::offset_of!(avifImage, imir) - 161usize];
    ["Offset of field: avifImage::exif"][::core::mem::offset_of!(avifImage, exif) - 168usize];
    ["Offset of field: avifImage::xmp"][::core::mem::offset_of!(avifImage, xmp) - 184usize];
    ["Offset of field: avifImage::properties"]
        [::core::mem::offset_of!(avifImage, properties) - 200usize];
    ["Offset of field: avifImage::numProperties"]
        [::core::mem::offset_of!(avifImage, numProperties) - 208usize];
    ["Offset of field: avifImage::gainMap"][::core::mem::offset_of!(avifImage, gainMap) - 216usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifRGBImage"][::core::mem::size_of::<avifRGBImage>() - 64usize];
    ["Alignment of avifRGBImage"][::core::mem::align_of::<avifRGBImage>() - 8usize];
    ["Offset of field: avifRGBImage::width"][::core::mem::offset_of!(avifRGBImage, width) - 0usize];
    ["Offset of field: avifRGBImage::height"]
        [::core::mem::offset_of!(avifRGBImage, height) - 4usize];
    ["Offset of field: avifRGBImage::depth"][::core::mem::offset_of!(avifRGBImage, depth) - 8usize];
    ["Offset of field: avifRGBImage::format"]
        [::core::mem::offset_of!(avifRGBImage, format) - 12usize];
    ["Offset of field: avifRGBImage::chromaUpsampling"]
        [::core::mem::offset_of!(avifRGBImage, chromaUpsampling) - 16usize];
    ["Offset of field: avifRGBImage::chromaDownsampling"]
        [::core::mem::offset_of!(avifRGBImage, chromaDownsampling) - 20usize];
    ["Offset of field: avifRGBImage::avoidLibYUV"]
        [::core::mem::offset_of!(avifRGBImage, avoidLibYUV) - 24usize];
    ["Offset of field: avifRGBImage::ignoreAlpha"]
        [::core::mem::offset_of!(avifRGBImage, ignoreAlpha) - 28usize];
    ["Offset of field: avifRGBImage::alphaPremultiplied"]
        [::core::mem::offset_of!(avifRGBImage, alphaPremultiplied) - 32usize];
    ["Offset of field: avifRGBImage::isFloat"]
        [::core::mem::offset_of!(avifRGBImage, isFloat) - 36usize];
    ["Offset of field: avifRGBImage::maxThreads"]
        [::core::mem::offset_of!(avifRGBImage, maxThreads) - 40usize];
    ["Offset of field: avifRGBImage::pixels"]
        [::core::mem::offset_of!(avifRGBImage, pixels) - 48usize];
    ["Offset of field: avifRGBImage::rowBytes"]
        [::core::mem::offset_of!(avifRGBImage, rowBytes) - 56usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifIO"][::core::mem::size_of::<avifIO>() - 48usize];
    ["Alignment of avifIO"][::core::mem::align_of::<avifIO>() - 8usize];
    ["Offset of field: avifIO::destroy"][::core::mem::offset_of!(avifIO, destroy) - 0usize];
    ["Offset of field: avifIO::read"][::core::mem::offset_of!(avifIO, read) - 8usize];
    ["Offset of field: avifIO::write"][::core::mem::offset_of!(avifIO, write) - 16usize];
    ["Offset of field: avifIO::sizeHint"][::core::mem::offset_of!(avifIO, sizeHint) - 24usize];
    ["Offset of field: avifIO::persistent"][::core::mem::offset_of!(avifIO, persistent) - 32usize];
    ["Offset of field: avifIO::data"][::core::mem::offset_of!(avifIO, data) - 40usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifIOStats"][::core::mem::size_of::<avifIOStats>() - 16usize];
    ["Alignment of avifIOStats"][::core::mem::align_of::<avifIOStats>() - 8usize];
    ["Offset of field: avifIOStats::colorOBUSize"]
        [::core::mem::offset_of!(avifIOStats, colorOBUSize) - 0usize];
    ["Offset of field: avifIOStats::alphaOBUSize"]
        [::core::mem::offset_of!(avifIOStats, alphaOBUSize) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifImageTiming"][::core::mem::size_of::<avifImageTiming>() - 40usize];
    ["Alignment of avifImageTiming"][::core::mem::align_of::<avifImageTiming>() - 8usize];
    ["Offset of field: avifImageTiming::timescale"]
        [::core::mem::offset_of!(avifImageTiming, timescale) - 0usize];
    ["Offset of field: avifImageTiming::pts"]
        [::core::mem::offset_of!(avifImageTiming, pts) - 8usize];
    ["Offset of field: avifImageTiming::ptsInTimescales"]
        [::core::mem::offset_of!(avifImageTiming, ptsInTimescales) - 16usize];
    ["Offset of field: avifImageTiming::duration"]
        [::core::mem::offset_of!(avifImageTiming, duration) - 24usize];
    ["Offset of field: avifImageTiming::durationInTimescales"]
        [::core::mem::offset_of!(avifImageTiming, durationInTimescales) - 32usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifDecoder"][::core::mem::size_of::<avifDecoder>() - 440usize];
    ["Alignment of avifDecoder"][::core::mem::align_of::<avifDecoder>() - 8usize];
    ["Offset of field: avifDecoder::codecChoice"]
        [::core::mem::offset_of!(avifDecoder, codecChoice) - 0usize];
    ["Offset of field: avifDecoder::maxThreads"]
        [::core::mem::offset_of!(avifDecoder, maxThreads) - 4usize];
    ["Offset of field: avifDecoder::requestedSource"]
        [::core::mem::offset_of!(avifDecoder, requestedSource) - 8usize];
    ["Offset of field: avifDecoder::allowProgressive"]
        [::core::mem::offset_of!(avifDecoder, allowProgressive) - 12usize];
    ["Offset of field: avifDecoder::allowIncremental"]
        [::core::mem::offset_of!(avifDecoder, allowIncremental) - 16usize];
    ["Offset of field: avifDecoder::ignoreExif"]
        [::core::mem::offset_of!(avifDecoder, ignoreExif) - 20usize];
    ["Offset of field: avifDecoder::ignoreXMP"]
        [::core::mem::offset_of!(avifDecoder, ignoreXMP) - 24usize];
    ["Offset of field: avifDecoder::imageSizeLimit"]
        [::core::mem::offset_of!(avifDecoder, imageSizeLimit) - 28usize];
    ["Offset of field: avifDecoder::imageDimensionLimit"]
        [::core::mem::offset_of!(avifDecoder, imageDimensionLimit) - 32usize];
    ["Offset of field: avifDecoder::imageCountLimit"]
        [::core::mem::offset_of!(avifDecoder, imageCountLimit) - 36usize];
    ["Offset of field: avifDecoder::strictFlags"]
        [::core::mem::offset_of!(avifDecoder, strictFlags) - 40usize];
    ["Offset of field: avifDecoder::image"][::core::mem::offset_of!(avifDecoder, image) - 48usize];
    ["Offset of field: avifDecoder::imageIndex"]
        [::core::mem::offset_of!(avifDecoder, imageIndex) - 56usize];
    ["Offset of field: avifDecoder::imageCount"]
        [::core::mem::offset_of!(avifDecoder, imageCount) - 60usize];
    ["Offset of field: avifDecoder::progressiveState"]
        [::core::mem::offset_of!(avifDecoder, progressiveState) - 64usize];
    ["Offset of field: avifDecoder::imageTiming"]
        [::core::mem::offset_of!(avifDecoder, imageTiming) - 72usize];
    ["Offset of field: avifDecoder::timescale"]
        [::core::mem::offset_of!(avifDecoder, timescale) - 112usize];
    ["Offset of field: avifDecoder::duration"]
        [::core::mem::offset_of!(avifDecoder, duration) - 120usize];
    ["Offset of field: avifDecoder::durationInTimescales"]
        [::core::mem::offset_of!(avifDecoder, durationInTimescales) - 128usize];
    ["Offset of field: avifDecoder::repetitionCount"]
        [::core::mem::offset_of!(avifDecoder, repetitionCount) - 136usize];
    ["Offset of field: avifDecoder::alphaPresent"]
        [::core::mem::offset_of!(avifDecoder, alphaPresent) - 140usize];
    ["Offset of field: avifDecoder::ioStats"]
        [::core::mem::offset_of!(avifDecoder, ioStats) - 144usize];
    ["Offset of field: avifDecoder::diag"][::core::mem::offset_of!(avifDecoder, diag) - 160usize];
    ["Offset of field: avifDecoder::io"][::core::mem::offset_of!(avifDecoder, io) - 416usize];
    ["Offset of field: avifDecoder::data"][::core::mem::offset_of!(avifDecoder, data) - 424usize];
    ["Offset of field: avifDecoder::imageSequenceTrackPresent"]
        [::core::mem::offset_of!(avifDecoder, imageSequenceTrackPresent) - 432usize];
    ["Offset of field: avifDecoder::imageContentToDecode"]
        [::core::mem::offset_of!(avifDecoder, imageContentToDecode) - 436usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifExtent"][::core::mem::size_of::<avifExtent>() - 16usize];
    ["Alignment of avifExtent"][::core::mem::align_of::<avifExtent>() - 8usize];
    ["Offset of field: avifExtent::offset"][::core::mem::offset_of!(avifExtent, offset) - 0usize];
    ["Offset of field: avifExtent::size"][::core::mem::offset_of!(avifExtent, size) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifScalingMode"][::core::mem::size_of::<avifScalingMode>() - 16usize];
    ["Alignment of avifScalingMode"][::core::mem::align_of::<avifScalingMode>() - 4usize];
    ["Offset of field: avifScalingMode::horizontal"]
        [::core::mem::offset_of!(avifScalingMode, horizontal) - 0usize];
    ["Offset of field: avifScalingMode::vertical"]
        [::core::mem::offset_of!(avifScalingMode, vertical) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of avifEncoder"][::core::mem::size_of::<avifEncoder>() - 408usize];
    ["Alignment of avifEncoder"][::core::mem::align_of::<avifEncoder>() - 8usize];
    ["Offset of field: avifEncoder::codecChoice"]
        [::core::mem::offset_of!(avifEncoder, codecChoice) - 0usize];
    ["Offset of field: avifEncoder::maxThreads"]
        [::core::mem::offset_of!(avifEncoder, maxThreads) - 4usize];
    ["Offset of field: avifEncoder::speed"][::core::mem::offset_of!(avifEncoder, speed) - 8usize];
    ["Offset of field: avifEncoder::keyframeInterval"]
        [::core::mem::offset_of!(avifEncoder, keyframeInterval) - 12usize];
    ["Offset of field: avifEncoder::timescale"]
        [::core::mem::offset_of!(avifEncoder, timescale) - 16usize];
    ["Offset of field: avifEncoder::repetitionCount"]
        [::core::mem::offset_of!(avifEncoder, repetitionCount) - 24usize];
    ["Offset of field: avifEncoder::extraLayerCount"]
        [::core::mem::offset_of!(avifEncoder, extraLayerCount) - 28usize];
    ["Offset of field: avifEncoder::quality"]
        [::core::mem::offset_of!(avifEncoder, quality) - 32usize];
    ["Offset of field: avifEncoder::qualityAlpha"]
        [::core::mem::offset_of!(avifEncoder, qualityAlpha) - 36usize];
    ["Offset of field: avifEncoder::minQuantizer"]
        [::core::mem::offset_of!(avifEncoder, minQuantizer) - 40usize];
    ["Offset of field: avifEncoder::maxQuantizer"]
        [::core::mem::offset_of!(avifEncoder, maxQuantizer) - 44usize];
    ["Offset of field: avifEncoder::minQuantizerAlpha"]
        [::core::mem::offset_of!(avifEncoder, minQuantizerAlpha) - 48usize];
    ["Offset of field: avifEncoder::maxQuantizerAlpha"]
        [::core::mem::offset_of!(avifEncoder, maxQuantizerAlpha) - 52usize];
    ["Offset of field: avifEncoder::tileRowsLog2"]
        [::core::mem::offset_of!(avifEncoder, tileRowsLog2) - 56usize];
    ["Offset of field: avifEncoder::tileColsLog2"]
        [::core::mem::offset_of!(avifEncoder, tileColsLog2) - 60usize];
    ["Offset of field: avifEncoder::autoTiling"]
        [::core::mem::offset_of!(avifEncoder, autoTiling) - 64usize];
    ["Offset of field: avifEncoder::scalingMode"]
        [::core::mem::offset_of!(avifEncoder, scalingMode) - 68usize];
    ["Offset of field: avifEncoder::ioStats"]
        [::core::mem::offset_of!(avifEncoder, ioStats) - 88usize];
    ["Offset of field: avifEncoder::diag"][::core::mem::offset_of!(avifEncoder, diag) - 104usize];
    ["Offset of field: avifEncoder::data"][::core::mem::offset_of!(avifEncoder, data) - 360usize];
    ["Offset of field: avifEncoder::csOptions"]
        [::core::mem::offset_of!(avifEncoder, csOptions) - 368usize];
    ["Offset of field: avifEncoder::headerFormat"]
        [::core::mem::offset_of!(avifEncoder, headerFormat) - 376usize];
    ["Offset of field: avifEncoder::qualityGainMap"]
        [::core::mem::offset_of!(avifEncoder, qualityGainMap) - 380usize];
    ["Offset of field: avifEncoder::creationTime"]
        [::core::mem::offset_of!(avifEncoder, creationTime) - 384usize];
    ["Offset of field: avifEncoder::modificationTime"]
        [::core::mem::offset_of!(avifEncoder, modificationTime) - 392usize];
    ["Offset of field: avifEncoder::sampleTransformRecipe"]
        [::core::mem::offset_of!(avifEncoder, sampleTransformRecipe) - 400usize];
};
impl avifPlanesFlag {
    pub const AVIF_PLANES_YUV: avifPlanesFlag = avifPlanesFlag(1);
    pub const AVIF_PLANES_A: avifPlanesFlag = avifPlanesFlag(2);
    pub const AVIF_PLANES_ALL: avifPlanesFlag = avifPlanesFlag(255);
}
impl avifChannelIndex {
    pub const AVIF_CHAN_Y: avifChannelIndex = avifChannelIndex(0);
    pub const AVIF_CHAN_U: avifChannelIndex = avifChannelIndex(1);
    pub const AVIF_CHAN_V: avifChannelIndex = avifChannelIndex(2);
    pub const AVIF_CHAN_A: avifChannelIndex = avifChannelIndex(3);
}
impl avifResult {
    pub const AVIF_RESULT_OK: avifResult = avifResult(0);
    pub const AVIF_RESULT_UNKNOWN_ERROR: avifResult = avifResult(1);
    pub const AVIF_RESULT_INVALID_FTYP: avifResult = avifResult(2);
    pub const AVIF_RESULT_NO_CONTENT: avifResult = avifResult(3);
    pub const AVIF_RESULT_NO_YUV_FORMAT_SELECTED: avifResult = avifResult(4);
    pub const AVIF_RESULT_REFORMAT_FAILED: avifResult = avifResult(5);
    pub const AVIF_RESULT_UNSUPPORTED_DEPTH: avifResult = avifResult(6);
    pub const AVIF_RESULT_ENCODE_COLOR_FAILED: avifResult = avifResult(7);
    pub const AVIF_RESULT_ENCODE_ALPHA_FAILED: avifResult = avifResult(8);
    pub const AVIF_RESULT_BMFF_PARSE_FAILED: avifResult = avifResult(9);
    pub const AVIF_RESULT_MISSING_IMAGE_ITEM: avifResult = avifResult(10);
    pub const AVIF_RESULT_DECODE_COLOR_FAILED: avifResult = avifResult(11);
    pub const AVIF_RESULT_DECODE_ALPHA_FAILED: avifResult = avifResult(12);
    pub const AVIF_RESULT_COLOR_ALPHA_SIZE_MISMATCH: avifResult = avifResult(13);
    pub const AVIF_RESULT_ISPE_SIZE_MISMATCH: avifResult = avifResult(14);
    pub const AVIF_RESULT_NO_CODEC_AVAILABLE: avifResult = avifResult(15);
    pub const AVIF_RESULT_NO_IMAGES_REMAINING: avifResult = avifResult(16);
    pub const AVIF_RESULT_INVALID_EXIF_PAYLOAD: avifResult = avifResult(17);
    pub const AVIF_RESULT_INVALID_IMAGE_GRID: avifResult = avifResult(18);
    pub const AVIF_RESULT_INVALID_CODEC_SPECIFIC_OPTION: avifResult = avifResult(19);
    pub const AVIF_RESULT_TRUNCATED_DATA: avifResult = avifResult(20);
    pub const AVIF_RESULT_IO_NOT_SET: avifResult = avifResult(21);
    pub const AVIF_RESULT_IO_ERROR: avifResult = avifResult(22);
    pub const AVIF_RESULT_WAITING_ON_IO: avifResult = avifResult(23);
    pub const AVIF_RESULT_INVALID_ARGUMENT: avifResult = avifResult(24);
    pub const AVIF_RESULT_NOT_IMPLEMENTED: avifResult = avifResult(25);
    pub const AVIF_RESULT_OUT_OF_MEMORY: avifResult = avifResult(26);
    pub const AVIF_RESULT_CANNOT_CHANGE_SETTING: avifResult = avifResult(27);
    pub const AVIF_RESULT_INCOMPATIBLE_IMAGE: avifResult = avifResult(28);
    pub const AVIF_RESULT_INTERNAL_ERROR: avifResult = avifResult(29);
    pub const AVIF_RESULT_ENCODE_GAIN_MAP_FAILED: avifResult = avifResult(30);
    pub const AVIF_RESULT_DECODE_GAIN_MAP_FAILED: avifResult = avifResult(31);
    pub const AVIF_RESULT_INVALID_TONE_MAPPED_IMAGE: avifResult = avifResult(32);
    pub const AVIF_RESULT_ENCODE_SAMPLE_TRANSFORM_FAILED: avifResult = avifResult(33);
    pub const AVIF_RESULT_DECODE_SAMPLE_TRANSFORM_FAILED: avifResult = avifResult(34);
    pub const AVIF_RESULT_NO_AV1_ITEMS_FOUND: avifResult = avifResult(10);
}
impl avifHeaderFormat {
    pub const AVIF_HEADER_DEFAULT: avifHeaderFormat = avifHeaderFormat(0);
    pub const AVIF_HEADER_FULL: avifHeaderFormat = avifHeaderFormat(0);
}
impl avifPixelFormat {
    pub const AVIF_PIXEL_FORMAT_NONE: avifPixelFormat = avifPixelFormat(0);
    pub const AVIF_PIXEL_FORMAT_YUV444: avifPixelFormat = avifPixelFormat(1);
    pub const AVIF_PIXEL_FORMAT_YUV422: avifPixelFormat = avifPixelFormat(2);
    pub const AVIF_PIXEL_FORMAT_YUV420: avifPixelFormat = avifPixelFormat(3);
    pub const AVIF_PIXEL_FORMAT_YUV400: avifPixelFormat = avifPixelFormat(4);
    pub const AVIF_PIXEL_FORMAT_COUNT: avifPixelFormat = avifPixelFormat(5);
}
impl avifChromaSamplePosition {
    pub const AVIF_CHROMA_SAMPLE_POSITION_UNKNOWN: avifChromaSamplePosition =
        avifChromaSamplePosition(0);
    pub const AVIF_CHROMA_SAMPLE_POSITION_VERTICAL: avifChromaSamplePosition =
        avifChromaSamplePosition(1);
    pub const AVIF_CHROMA_SAMPLE_POSITION_COLOCATED: avifChromaSamplePosition =
        avifChromaSamplePosition(2);
    pub const AVIF_CHROMA_SAMPLE_POSITION_RESERVED: avifChromaSamplePosition =
        avifChromaSamplePosition(3);
}
impl avifRange {
    #[doc = "<- Y  [16..235],  UV  [16..240]  (bit depth 8) */\n/**<- Y  [64..940],  UV  [64..960]  (bit depth 10) */\n/**<- Y [256..3760], UV [256..3840] (bit depth 12)"]
    pub const AVIF_RANGE_LIMITED: avifRange = avifRange(0);
    #[doc = "<- [0..255]  (bit depth 8) */\n/**<- [0..1023] (bit depth 10) */\n/**<- [0..4095] (bit depth 12)"]
    pub const AVIF_RANGE_FULL: avifRange = avifRange(1);
}
impl avifTransformFlag {
    pub const AVIF_TRANSFORM_NONE: avifTransformFlag = avifTransformFlag(0);
    pub const AVIF_TRANSFORM_PASP: avifTransformFlag = avifTransformFlag(1);
    pub const AVIF_TRANSFORM_CLAP: avifTransformFlag = avifTransformFlag(2);
    pub const AVIF_TRANSFORM_IROT: avifTransformFlag = avifTransformFlag(4);
    pub const AVIF_TRANSFORM_IMIR: avifTransformFlag = avifTransformFlag(8);
}
impl avifSampleTransformRecipe {
    pub const AVIF_SAMPLE_TRANSFORM_NONE: avifSampleTransformRecipe = avifSampleTransformRecipe(0);
    pub const AVIF_SAMPLE_TRANSFORM_BIT_DEPTH_EXTENSION_8B_8B: avifSampleTransformRecipe =
        avifSampleTransformRecipe(1);
    pub const AVIF_SAMPLE_TRANSFORM_BIT_DEPTH_EXTENSION_12B_4B: avifSampleTransformRecipe =
        avifSampleTransformRecipe(2);
    pub const AVIF_SAMPLE_TRANSFORM_BIT_DEPTH_EXTENSION_12B_8B_OVERLAP_4B:
        avifSampleTransformRecipe = avifSampleTransformRecipe(3);
}
impl avifRGBFormat {
    pub const AVIF_RGB_FORMAT_RGB: avifRGBFormat = avifRGBFormat(0);
    pub const AVIF_RGB_FORMAT_RGBA: avifRGBFormat = avifRGBFormat(1);
    pub const AVIF_RGB_FORMAT_ARGB: avifRGBFormat = avifRGBFormat(2);
    pub const AVIF_RGB_FORMAT_BGR: avifRGBFormat = avifRGBFormat(3);
    pub const AVIF_RGB_FORMAT_BGRA: avifRGBFormat = avifRGBFormat(4);
    pub const AVIF_RGB_FORMAT_ABGR: avifRGBFormat = avifRGBFormat(5);
    pub const AVIF_RGB_FORMAT_RGB_565: avifRGBFormat = avifRGBFormat(6);
    pub const AVIF_RGB_FORMAT_GRAY: avifRGBFormat = avifRGBFormat(7);
    pub const AVIF_RGB_FORMAT_GRAYA: avifRGBFormat = avifRGBFormat(8);
    pub const AVIF_RGB_FORMAT_AGRAY: avifRGBFormat = avifRGBFormat(9);
    pub const AVIF_RGB_FORMAT_COUNT: avifRGBFormat = avifRGBFormat(10);
}
impl avifChromaUpsampling {
    pub const AVIF_CHROMA_UPSAMPLING_AUTOMATIC: avifChromaUpsampling = avifChromaUpsampling(0);
    pub const AVIF_CHROMA_UPSAMPLING_FASTEST: avifChromaUpsampling = avifChromaUpsampling(1);
    pub const AVIF_CHROMA_UPSAMPLING_BEST_QUALITY: avifChromaUpsampling = avifChromaUpsampling(2);
    pub const AVIF_CHROMA_UPSAMPLING_NEAREST: avifChromaUpsampling = avifChromaUpsampling(3);
    pub const AVIF_CHROMA_UPSAMPLING_BILINEAR: avifChromaUpsampling = avifChromaUpsampling(4);
}
impl avifChromaDownsampling {
    pub const AVIF_CHROMA_DOWNSAMPLING_AUTOMATIC: avifChromaDownsampling =
        avifChromaDownsampling(0);
    pub const AVIF_CHROMA_DOWNSAMPLING_FASTEST: avifChromaDownsampling = avifChromaDownsampling(1);
    pub const AVIF_CHROMA_DOWNSAMPLING_BEST_QUALITY: avifChromaDownsampling =
        avifChromaDownsampling(2);
    pub const AVIF_CHROMA_DOWNSAMPLING_AVERAGE: avifChromaDownsampling = avifChromaDownsampling(3);
    pub const AVIF_CHROMA_DOWNSAMPLING_SHARP_YUV: avifChromaDownsampling =
        avifChromaDownsampling(4);
}
impl avifCodecChoice {
    pub const AVIF_CODEC_CHOICE_AUTO: avifCodecChoice = avifCodecChoice(0);
    pub const AVIF_CODEC_CHOICE_AOM: avifCodecChoice = avifCodecChoice(1);
    pub const AVIF_CODEC_CHOICE_DAV1D: avifCodecChoice = avifCodecChoice(2);
    pub const AVIF_CODEC_CHOICE_LIBGAV1: avifCodecChoice = avifCodecChoice(3);
    pub const AVIF_CODEC_CHOICE_RAV1E: avifCodecChoice = avifCodecChoice(4);
    pub const AVIF_CODEC_CHOICE_SVT: avifCodecChoice = avifCodecChoice(5);
    pub const AVIF_CODEC_CHOICE_AVM: avifCodecChoice = avifCodecChoice(6);
}
impl avifCodecFlag {
    pub const AVIF_CODEC_FLAG_CAN_DECODE: avifCodecFlag = avifCodecFlag(1);
    pub const AVIF_CODEC_FLAG_CAN_ENCODE: avifCodecFlag = avifCodecFlag(2);
}
impl avifStrictFlag {
    pub const AVIF_STRICT_DISABLED: avifStrictFlag = avifStrictFlag(0);
    pub const AVIF_STRICT_PIXI_REQUIRED: avifStrictFlag = avifStrictFlag(1);
    pub const AVIF_STRICT_CLAP_VALID: avifStrictFlag = avifStrictFlag(2);
    pub const AVIF_STRICT_ALPHA_ISPE_REQUIRED: avifStrictFlag = avifStrictFlag(4);
    pub const AVIF_STRICT_ENABLED: avifStrictFlag = avifStrictFlag(7);
}
impl avifDecoderSource {
    pub const AVIF_DECODER_SOURCE_AUTO: avifDecoderSource = avifDecoderSource(0);
    pub const AVIF_DECODER_SOURCE_PRIMARY_ITEM: avifDecoderSource = avifDecoderSource(1);
    pub const AVIF_DECODER_SOURCE_TRACKS: avifDecoderSource = avifDecoderSource(2);
}
impl avifProgressiveState {
    pub const AVIF_PROGRESSIVE_STATE_UNAVAILABLE: avifProgressiveState = avifProgressiveState(0);
    pub const AVIF_PROGRESSIVE_STATE_AVAILABLE: avifProgressiveState = avifProgressiveState(1);
    pub const AVIF_PROGRESSIVE_STATE_ACTIVE: avifProgressiveState = avifProgressiveState(2);
}
impl avifImageContentTypeFlag {
    pub const AVIF_IMAGE_CONTENT_NONE: avifImageContentTypeFlag = avifImageContentTypeFlag(0);
    pub const AVIF_IMAGE_CONTENT_COLOR_AND_ALPHA: avifImageContentTypeFlag =
        avifImageContentTypeFlag(3);
    pub const AVIF_IMAGE_CONTENT_GAIN_MAP: avifImageContentTypeFlag = avifImageContentTypeFlag(4);
    pub const AVIF_IMAGE_CONTENT_ALL: avifImageContentTypeFlag = avifImageContentTypeFlag(7);
    pub const AVIF_IMAGE_CONTENT_SAMPLE_TRANSFORMS: avifImageContentTypeFlag =
        avifImageContentTypeFlag(8);
    pub const AVIF_IMAGE_CONTENT_DECODE_DEFAULT: avifImageContentTypeFlag =
        avifImageContentTypeFlag(3);
}
impl avifAddImageFlag {
    pub const AVIF_ADD_IMAGE_FLAG_NONE: avifAddImageFlag = avifAddImageFlag(0);
    pub const AVIF_ADD_IMAGE_FLAG_FORCE_KEYFRAME: avifAddImageFlag = avifAddImageFlag(1);
    pub const AVIF_ADD_IMAGE_FLAG_SINGLE: avifAddImageFlag = avifAddImageFlag(2);
}
unsafe extern "C" {
    pub fn avifVersion() -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifCodecVersions(outBuffer: *mut ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn avifLibYUVVersion() -> ::core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn avifAlloc(size: usize) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn avifFree(p: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn avifResultToString(result: avifResult) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifRWDataRealloc(raw: *mut avifRWData, newSize: usize) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRWDataSet(raw: *mut avifRWData, data: *const u8, len: usize) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRWDataFree(raw: *mut avifRWData);
}
unsafe extern "C" {
    pub fn avifGetExifTiffHeaderOffset(
        exif: *const u8,
        exifSize: usize,
        offset: *mut usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifGetExifOrientationOffset(
        exif: *const u8,
        exifSize: usize,
        offset: *mut usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifPixelFormatToString(format: avifPixelFormat) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifGetPixelFormatInfo(format: avifPixelFormat, info: *mut avifPixelFormatInfo);
}
unsafe extern "C" {
    pub fn avifColorPrimariesGetValues(acp: avifColorPrimaries, outPrimaries: *mut f32);
}
unsafe extern "C" {
    pub fn avifColorPrimariesFind(
        inPrimaries: *const f32,
        outName: *mut *const ::core::ffi::c_char,
    ) -> avifColorPrimaries;
}
unsafe extern "C" {
    pub fn avifTransferCharacteristicsGetGamma(
        atc: avifTransferCharacteristics,
        gamma: *mut f32,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifTransferCharacteristicsFindByGamma(gamma: f32) -> avifTransferCharacteristics;
}
unsafe extern "C" {
    pub fn avifDiagnosticsClearError(diag: *mut avifDiagnostics);
}
unsafe extern "C" {
    pub fn avifDoubleToSignedFraction(v: f64, fraction: *mut avifSignedFraction) -> avifBool;
}
unsafe extern "C" {
    pub fn avifDoubleToUnsignedFraction(v: f64, fraction: *mut avifUnsignedFraction) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCropRectFromCleanApertureBox(
        cropRect: *mut avifCropRect,
        clap: *const avifCleanApertureBox,
        imageW: u32,
        imageH: u32,
        diag: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCleanApertureBoxFromCropRect(
        clap: *mut avifCleanApertureBox,
        cropRect: *const avifCropRect,
        imageW: u32,
        imageH: u32,
        diag: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCropRectRequiresUpsampling(
        cropRect: *const avifCropRect,
        yuvFormat: avifPixelFormat,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCropRectConvertCleanApertureBox(
        arg1: *mut avifCropRect,
        arg2: *const avifCleanApertureBox,
        arg3: u32,
        arg4: u32,
        arg5: avifPixelFormat,
        arg6: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCleanApertureBoxConvertCropRect(
        arg1: *mut avifCleanApertureBox,
        arg2: *const avifCropRect,
        arg3: u32,
        arg4: u32,
        arg5: avifPixelFormat,
        arg6: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifGainMapCreate() -> *mut avifGainMap;
}
unsafe extern "C" {
    pub fn avifGainMapDestroy(gainMap: *mut avifGainMap);
}
unsafe extern "C" {
    pub fn avifImageCreate(
        width: u32,
        height: u32,
        depth: u32,
        yuvFormat: avifPixelFormat,
    ) -> *mut avifImage;
}
unsafe extern "C" {
    pub fn avifImageCreateEmpty() -> *mut avifImage;
}
unsafe extern "C" {
    pub fn avifImageCopy(
        dstImage: *mut avifImage,
        srcImage: *const avifImage,
        planes: avifPlanesFlags,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageSetViewRect(
        dstImage: *mut avifImage,
        srcImage: *const avifImage,
        rect: *const avifCropRect,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageDestroy(image: *mut avifImage);
}
unsafe extern "C" {
    pub fn avifImageSetProfileICC(
        image: *mut avifImage,
        icc: *const u8,
        iccSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageSetMetadataExif(
        image: *mut avifImage,
        exif: *const u8,
        exifSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageSetMetadataXMP(
        image: *mut avifImage,
        xmp: *const u8,
        xmpSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageAllocatePlanes(image: *mut avifImage, planes: avifPlanesFlags) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageFreePlanes(image: *mut avifImage, planes: avifPlanesFlags);
}
unsafe extern "C" {
    pub fn avifImageStealPlanes(
        dstImage: *mut avifImage,
        srcImage: *mut avifImage,
        planes: avifPlanesFlags,
    );
}
unsafe extern "C" {
    pub fn avifImageAddOpaqueProperty(
        image: *mut avifImage,
        boxtype: *const u8,
        data: *const u8,
        dataSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageAddUUIDProperty(
        image: *mut avifImage,
        uuid: *const u8,
        data: *const u8,
        dataSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageScale(
        image: *mut avifImage,
        dstWidth: u32,
        dstHeight: u32,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBFormatChannelCount(format: avifRGBFormat) -> u32;
}
unsafe extern "C" {
    pub fn avifRGBFormatHasAlpha(format: avifRGBFormat) -> avifBool;
}
unsafe extern "C" {
    pub fn avifRGBFormatIsGray(format: avifRGBFormat) -> avifBool;
}
unsafe extern "C" {
    pub fn avifRGBImageSetDefaults(rgb: *mut avifRGBImage, image: *const avifImage);
}
unsafe extern "C" {
    pub fn avifRGBImagePixelSize(rgb: *const avifRGBImage) -> u32;
}
unsafe extern "C" {
    pub fn avifRGBImageAllocatePixels(rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageFreePixels(rgb: *mut avifRGBImage);
}
unsafe extern "C" {
    pub fn avifImageRGBToYUV(image: *mut avifImage, rgb: *const avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageYUVToRGB(image: *const avifImage, rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImagePremultiplyAlpha(rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageUnpremultiplyAlpha(rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifFullToLimitedY(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifFullToLimitedUV(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifLimitedToFullY(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifLimitedToFullUV(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifCodecName(
        choice: avifCodecChoice,
        requiredFlags: avifCodecFlags,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifCodecChoiceFromName(name: *const ::core::ffi::c_char) -> avifCodecChoice;
}
unsafe extern "C" {
    pub fn avifIOCreateMemoryReader(data: *const u8, size: usize) -> *mut avifIO;
}
unsafe extern "C" {
    pub fn avifIOCreateFileReader(filename: *const ::core::ffi::c_char) -> *mut avifIO;
}
unsafe extern "C" {
    pub fn avifIODestroy(io: *mut avifIO);
}
unsafe extern "C" {
    pub fn avifProgressiveStateToString(
        progressiveState: avifProgressiveState,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifDecoderCreate() -> *mut avifDecoder;
}
unsafe extern "C" {
    pub fn avifDecoderDestroy(decoder: *mut avifDecoder);
}
unsafe extern "C" {
    pub fn avifDecoderRead(decoder: *mut avifDecoder, image: *mut avifImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderReadMemory(
        decoder: *mut avifDecoder,
        image: *mut avifImage,
        data: *const u8,
        size: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderReadFile(
        decoder: *mut avifDecoder,
        image: *mut avifImage,
        filename: *const ::core::ffi::c_char,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderSetSource(decoder: *mut avifDecoder, source: avifDecoderSource)
    -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderSetIO(decoder: *mut avifDecoder, io: *mut avifIO);
}
unsafe extern "C" {
    pub fn avifDecoderSetIOMemory(
        decoder: *mut avifDecoder,
        data: *const u8,
        size: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderSetIOFile(
        decoder: *mut avifDecoder,
        filename: *const ::core::ffi::c_char,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderParse(decoder: *mut avifDecoder) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderNextImage(decoder: *mut avifDecoder) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderNthImage(decoder: *mut avifDecoder, frameIndex: u32) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderReset(decoder: *mut avifDecoder) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderIsKeyframe(decoder: *const avifDecoder, frameIndex: u32) -> avifBool;
}
unsafe extern "C" {
    pub fn avifDecoderNearestKeyframe(decoder: *const avifDecoder, frameIndex: u32) -> u32;
}
unsafe extern "C" {
    pub fn avifDecoderNthImageTiming(
        decoder: *const avifDecoder,
        frameIndex: u32,
        outTiming: *mut avifImageTiming,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderDecodedRowCount(decoder: *const avifDecoder) -> u32;
}
unsafe extern "C" {
    pub fn avifDecoderNthImageMaxExtent(
        decoder: *const avifDecoder,
        frameIndex: u32,
        outExtent: *mut avifExtent,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderCreate() -> *mut avifEncoder;
}
unsafe extern "C" {
    pub fn avifEncoderWrite(
        encoder: *mut avifEncoder,
        image: *const avifImage,
        output: *mut avifRWData,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderDestroy(encoder: *mut avifEncoder);
}
unsafe extern "C" {
    pub fn avifEncoderAddImage(
        encoder: *mut avifEncoder,
        image: *const avifImage,
        durationInTimescales: u64,
        addImageFlags: avifAddImageFlags,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderAddImageGrid(
        encoder: *mut avifEncoder,
        gridCols: u32,
        gridRows: u32,
        cellImages: *const *const avifImage,
        addImageFlags: avifAddImageFlags,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderFinish(encoder: *mut avifEncoder, output: *mut avifRWData) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderSetCodecSpecificOption(
        encoder: *mut avifEncoder,
        key: *const ::core::ffi::c_char,
        value: *const ::core::ffi::c_char,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderGetGainMapSizeBytes(encoder: *mut avifEncoder) -> usize;
}
unsafe extern "C" {
    pub fn avifImageUsesU16(image: *const avifImage) -> avifBool;
}
unsafe extern "C" {
    pub fn avifImageIsOpaque(image: *const avifImage) -> avifBool;
}
unsafe extern "C" {
    pub fn avifImagePlane(image: *const avifImage, channel: ::core::ffi::c_int) -> *mut u8;
}
unsafe extern "C" {
    pub fn avifImagePlaneRowBytes(image: *const avifImage, channel: ::core::ffi::c_int) -> u32;
}
unsafe extern "C" {
    pub fn avifImagePlaneWidth(image: *const avifImage, channel: ::core::ffi::c_int) -> u32;
}
unsafe extern "C" {
    pub fn avifImagePlaneHeight(image: *const avifImage, channel: ::core::ffi::c_int) -> u32;
}
unsafe extern "C" {
    pub fn avifPeekCompatibleFileType(input: *const avifROData) -> avifBool;
}
unsafe extern "C" {
    pub fn avifImageApplyGainMap(
        baseImage: *const avifImage,
        gainMap: *const avifGainMap,
        hdrHeadroom: f32,
        outputColorPrimaries: avifColorPrimaries,
        outputTransferCharacteristics: avifTransferCharacteristics,
        toneMappedImage: *mut avifRGBImage,
        clli: *mut avifContentLightLevelInformationBox,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageApplyGainMap(
        baseImage: *const avifRGBImage,
        baseColorPrimaries: avifColorPrimaries,
        baseTransferCharacteristics: avifTransferCharacteristics,
        gainMap: *const avifGainMap,
        hdrHeadroom: f32,
        outputColorPrimaries: avifColorPrimaries,
        outputTransferCharacteristics: avifTransferCharacteristics,
        toneMappedImage: *mut avifRGBImage,
        clli: *mut avifContentLightLevelInformationBox,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageComputeGainMap(
        baseRgbImage: *const avifRGBImage,
        baseColorPrimaries: avifColorPrimaries,
        baseTransferCharacteristics: avifTransferCharacteristics,
        altRgbImage: *const avifRGBImage,
        altColorPrimaries: avifColorPrimaries,
        altTransferCharacteristics: avifTransferCharacteristics,
        gainMap: *mut avifGainMap,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageComputeGainMap(
        baseImage: *const avifImage,
        altImage: *const avifImage,
        gainMap: *mut avifGainMap,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
