/* automatically generated by rust-bindgen 0.72.1 */

pub type avifBool = ::core::ffi::c_int;
pub type avifPlanesFlags = u32;
pub type avifHeaderFormatFlags = ::core::ffi::c_int;
pub type avifTransformFlags = u32;
pub type avifCodecFlags = u32;
pub type avifIODestroyFunc = ::core::option::Option<unsafe extern "C" fn(io: *mut avifIO)>;
pub type avifIOReadFunc = ::core::option::Option<
    unsafe extern "C" fn(
        io: *mut avifIO,
        readFlags: u32,
        offset: u64,
        size: usize,
        out: *mut avifROData,
    ) -> avifResult,
>;
pub type avifIOWriteFunc = ::core::option::Option<
    unsafe extern "C" fn(
        io: *mut avifIO,
        writeFlags: u32,
        offset: u64,
        data: *const u8,
        size: usize,
    ) -> avifResult,
>;
pub type avifStrictFlags = u32;
pub type avifImageContentTypeFlags = u32;
pub type avifAddImageFlags = u32;
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifPlanesFlag(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChannelIndex(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifResult(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifHeaderFormat(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifROData {
    pub data: *const u8,
    pub size: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifRWData {
    pub data: *mut u8,
    pub size: usize,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifPixelFormat(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifPixelFormatInfo {
    pub monochrome: avifBool,
    pub chromaShiftX: ::core::ffi::c_int,
    pub chromaShiftY: ::core::ffi::c_int,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChromaSamplePosition(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifRange(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifColorPrimaries(pub u16);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifTransferCharacteristics(pub u16);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifMatrixCoefficients(pub u16);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifDiagnostics {
    pub error: [::core::ffi::c_char; 256usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifFraction {
    pub n: i32,
    pub d: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifSignedFraction {
    pub n: i32,
    pub d: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifUnsignedFraction {
    pub n: u32,
    pub d: u32,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifTransformFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifPixelAspectRatioBox {
    pub hSpacing: u32,
    pub vSpacing: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifCleanApertureBox {
    pub widthN: u32,
    pub widthD: u32,
    pub heightN: u32,
    pub heightD: u32,
    pub horizOffN: u32,
    pub horizOffD: u32,
    pub vertOffN: u32,
    pub vertOffD: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifImageRotation {
    pub angle: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifImageMirror {
    pub axis: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifCropRect {
    pub x: u32,
    pub y: u32,
    pub width: u32,
    pub height: u32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifContentLightLevelInformationBox {
    pub maxCLL: u16,
    pub maxPALL: u16,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifGainMap {
    pub image: *mut avifImage,
    pub gainMapMin: [avifSignedFraction; 3usize],
    pub gainMapMax: [avifSignedFraction; 3usize],
    pub gainMapGamma: [avifUnsignedFraction; 3usize],
    pub baseOffset: [avifSignedFraction; 3usize],
    pub alternateOffset: [avifSignedFraction; 3usize],
    pub baseHdrHeadroom: avifUnsignedFraction,
    pub alternateHdrHeadroom: avifUnsignedFraction,
    pub useBaseColorSpace: avifBool,
    pub altICC: avifRWData,
    pub altColorPrimaries: avifColorPrimaries,
    pub altTransferCharacteristics: avifTransferCharacteristics,
    pub altMatrixCoefficients: avifMatrixCoefficients,
    pub altYUVRange: avifRange,
    pub altDepth: u32,
    pub altPlaneCount: u32,
    pub altCLLI: avifContentLightLevelInformationBox,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifSampleTransformRecipe(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifImageItemProperty {
    pub boxtype: [u8; 4usize],
    pub usertype: [u8; 16usize],
    pub boxPayload: avifRWData,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifImage {
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub yuvFormat: avifPixelFormat,
    pub yuvRange: avifRange,
    pub yuvChromaSamplePosition: avifChromaSamplePosition,
    pub yuvPlanes: [*mut u8; 3usize],
    pub yuvRowBytes: [u32; 3usize],
    pub imageOwnsYUVPlanes: avifBool,
    pub alphaPlane: *mut u8,
    pub alphaRowBytes: u32,
    pub imageOwnsAlphaPlane: avifBool,
    pub alphaPremultiplied: avifBool,
    pub icc: avifRWData,
    pub colorPrimaries: avifColorPrimaries,
    pub transferCharacteristics: avifTransferCharacteristics,
    pub matrixCoefficients: avifMatrixCoefficients,
    pub clli: avifContentLightLevelInformationBox,
    pub transformFlags: avifTransformFlags,
    pub pasp: avifPixelAspectRatioBox,
    pub clap: avifCleanApertureBox,
    pub irot: avifImageRotation,
    pub imir: avifImageMirror,
    pub exif: avifRWData,
    pub xmp: avifRWData,
    pub properties: *mut avifImageItemProperty,
    pub numProperties: usize,
    pub gainMap: *mut avifGainMap,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifRGBFormat(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChromaUpsampling(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifChromaDownsampling(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifRGBImage {
    pub width: u32,
    pub height: u32,
    pub depth: u32,
    pub format: avifRGBFormat,
    pub chromaUpsampling: avifChromaUpsampling,
    pub chromaDownsampling: avifChromaDownsampling,
    pub avoidLibYUV: avifBool,
    pub ignoreAlpha: avifBool,
    pub alphaPremultiplied: avifBool,
    pub isFloat: avifBool,
    pub maxThreads: ::core::ffi::c_int,
    pub pixels: *mut u8,
    pub rowBytes: u32,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifCodecChoice(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifCodecFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifIO {
    pub destroy: avifIODestroyFunc,
    pub read: avifIOReadFunc,
    pub write: avifIOWriteFunc,
    pub sizeHint: u64,
    pub persistent: avifBool,
    pub data: *mut ::core::ffi::c_void,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifStrictFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifIOStats {
    pub colorOBUSize: usize,
    pub alphaOBUSize: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifDecoderData {
    _unused: [u8; 0],
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifDecoderSource(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug, Copy, Clone, PartialOrd, PartialEq)]
pub struct avifImageTiming {
    pub timescale: u64,
    pub pts: f64,
    pub ptsInTimescales: u64,
    pub duration: f64,
    pub durationInTimescales: u64,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifProgressiveState(pub ::core::ffi::c_uint);
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifImageContentTypeFlag(pub ::core::ffi::c_uint);
#[repr(C)]
#[derive(Debug)]
pub struct avifDecoder {
    pub codecChoice: avifCodecChoice,
    pub maxThreads: ::core::ffi::c_int,
    pub requestedSource: avifDecoderSource,
    pub allowProgressive: avifBool,
    pub allowIncremental: avifBool,
    pub ignoreExif: avifBool,
    pub ignoreXMP: avifBool,
    pub imageSizeLimit: u32,
    pub imageDimensionLimit: u32,
    pub imageCountLimit: u32,
    pub strictFlags: avifStrictFlags,
    pub image: *mut avifImage,
    pub imageIndex: ::core::ffi::c_int,
    pub imageCount: ::core::ffi::c_int,
    pub progressiveState: avifProgressiveState,
    pub imageTiming: avifImageTiming,
    pub timescale: u64,
    pub duration: f64,
    pub durationInTimescales: u64,
    pub repetitionCount: ::core::ffi::c_int,
    pub alphaPresent: avifBool,
    pub ioStats: avifIOStats,
    pub diag: avifDiagnostics,
    pub io: *mut avifIO,
    pub data: *mut avifDecoderData,
    pub imageSequenceTrackPresent: avifBool,
    pub imageContentToDecode: avifImageContentTypeFlags,
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifExtent {
    pub offset: u64,
    pub size: usize,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifEncoderData {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct avifCodecSpecificOptions {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone, Hash, PartialOrd, Ord, PartialEq, Eq)]
pub struct avifScalingMode {
    pub horizontal: avifFraction,
    pub vertical: avifFraction,
}
#[repr(C)]
#[derive(Debug)]
pub struct avifEncoder {
    pub codecChoice: avifCodecChoice,
    pub maxThreads: ::core::ffi::c_int,
    pub speed: ::core::ffi::c_int,
    pub keyframeInterval: ::core::ffi::c_int,
    pub timescale: u64,
    pub repetitionCount: ::core::ffi::c_int,
    pub extraLayerCount: u32,
    pub quality: ::core::ffi::c_int,
    pub qualityAlpha: ::core::ffi::c_int,
    pub minQuantizer: ::core::ffi::c_int,
    pub maxQuantizer: ::core::ffi::c_int,
    pub minQuantizerAlpha: ::core::ffi::c_int,
    pub maxQuantizerAlpha: ::core::ffi::c_int,
    pub tileRowsLog2: ::core::ffi::c_int,
    pub tileColsLog2: ::core::ffi::c_int,
    pub autoTiling: avifBool,
    pub scalingMode: avifScalingMode,
    pub ioStats: avifIOStats,
    pub diag: avifDiagnostics,
    pub data: *mut avifEncoderData,
    pub csOptions: *mut avifCodecSpecificOptions,
    pub headerFormat: avifHeaderFormatFlags,
    pub qualityGainMap: ::core::ffi::c_int,
    pub creationTime: u64,
    pub modificationTime: u64,
    pub sampleTransformRecipe: avifSampleTransformRecipe,
}
#[repr(transparent)]
#[derive(Debug, Clone, Hash, PartialEq, Eq, Copy, PartialOrd, Ord)]
pub struct avifAddImageFlag(pub ::core::ffi::c_uint);
pub const AVIF_VERSION_MAJOR: u32 = 1;
pub const AVIF_VERSION_MINOR: u32 = 4;
pub const AVIF_VERSION_PATCH: u32 = 2;
pub const AVIF_VERSION_DEVEL: u32 = 0;
pub const AVIF_VERSION: u32 = 1040200;
pub const AVIF_TRUE: u32 = 1;
pub const AVIF_FALSE: u32 = 0;
pub const AVIF_DIAGNOSTICS_ERROR_BUFFER_SIZE: u32 = 256;
pub const AVIF_DEFAULT_IMAGE_SIZE_LIMIT: u32 = 268435456;
pub const AVIF_DEFAULT_IMAGE_DIMENSION_LIMIT: u32 = 32768;
pub const AVIF_DEFAULT_IMAGE_COUNT_LIMIT: u32 = 2592000;
pub const AVIF_QUALITY_DEFAULT: i32 = -1;
pub const AVIF_QUALITY_WORST: u32 = 0;
pub const AVIF_QUALITY_BEST: u32 = 100;
pub const AVIF_QUALITY_LOSSLESS: u32 = 100;
pub const AVIF_QUANTIZER_LOSSLESS: u32 = 0;
pub const AVIF_QUANTIZER_BEST_QUALITY: u32 = 0;
pub const AVIF_QUANTIZER_WORST_QUALITY: u32 = 63;
pub const AVIF_PLANE_COUNT_YUV: u32 = 3;
pub const AVIF_SPEED_DEFAULT: i32 = -1;
pub const AVIF_SPEED_SLOWEST: u32 = 0;
pub const AVIF_SPEED_FASTEST: u32 = 10;
pub const AVIF_REPETITION_COUNT_INFINITE: i32 = -1;
pub const AVIF_REPETITION_COUNT_UNKNOWN: i32 = -2;
pub const AVIF_MAX_AV1_LAYER_COUNT: u32 = 4;
pub const AVIF_COLOR_PRIMARIES_UNKNOWN: avifColorPrimaries = avifColorPrimaries(0);
pub const AVIF_COLOR_PRIMARIES_BT709: avifColorPrimaries = avifColorPrimaries(1);
pub const AVIF_COLOR_PRIMARIES_SRGB: avifColorPrimaries = avifColorPrimaries(1);
pub const AVIF_COLOR_PRIMARIES_IEC61966_2_4: avifColorPrimaries = avifColorPrimaries(1);
pub const AVIF_COLOR_PRIMARIES_UNSPECIFIED: avifColorPrimaries = avifColorPrimaries(2);
pub const AVIF_COLOR_PRIMARIES_BT470M: avifColorPrimaries = avifColorPrimaries(4);
pub const AVIF_COLOR_PRIMARIES_BT470BG: avifColorPrimaries = avifColorPrimaries(5);
pub const AVIF_COLOR_PRIMARIES_BT601: avifColorPrimaries = avifColorPrimaries(6);
pub const AVIF_COLOR_PRIMARIES_SMPTE240: avifColorPrimaries = avifColorPrimaries(7);
pub const AVIF_COLOR_PRIMARIES_GENERIC_FILM: avifColorPrimaries = avifColorPrimaries(8);
pub const AVIF_COLOR_PRIMARIES_BT2020: avifColorPrimaries = avifColorPrimaries(9);
pub const AVIF_COLOR_PRIMARIES_BT2100: avifColorPrimaries = avifColorPrimaries(9);
pub const AVIF_COLOR_PRIMARIES_XYZ: avifColorPrimaries = avifColorPrimaries(10);
pub const AVIF_COLOR_PRIMARIES_SMPTE431: avifColorPrimaries = avifColorPrimaries(11);
pub const AVIF_COLOR_PRIMARIES_SMPTE432: avifColorPrimaries = avifColorPrimaries(12);
pub const AVIF_COLOR_PRIMARIES_DCI_P3: avifColorPrimaries = avifColorPrimaries(12);
pub const AVIF_COLOR_PRIMARIES_EBU3213: avifColorPrimaries = avifColorPrimaries(22);
pub const AVIF_TRANSFER_CHARACTERISTICS_UNKNOWN: avifTransferCharacteristics =
    avifTransferCharacteristics(0);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT709: avifTransferCharacteristics =
    avifTransferCharacteristics(1);
pub const AVIF_TRANSFER_CHARACTERISTICS_UNSPECIFIED: avifTransferCharacteristics =
    avifTransferCharacteristics(2);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT470M: avifTransferCharacteristics =
    avifTransferCharacteristics(4);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT470BG: avifTransferCharacteristics =
    avifTransferCharacteristics(5);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT601: avifTransferCharacteristics =
    avifTransferCharacteristics(6);
pub const AVIF_TRANSFER_CHARACTERISTICS_SMPTE240: avifTransferCharacteristics =
    avifTransferCharacteristics(7);
pub const AVIF_TRANSFER_CHARACTERISTICS_LINEAR: avifTransferCharacteristics =
    avifTransferCharacteristics(8);
pub const AVIF_TRANSFER_CHARACTERISTICS_LOG100: avifTransferCharacteristics =
    avifTransferCharacteristics(9);
pub const AVIF_TRANSFER_CHARACTERISTICS_LOG100_SQRT10: avifTransferCharacteristics =
    avifTransferCharacteristics(10);
pub const AVIF_TRANSFER_CHARACTERISTICS_IEC61966: avifTransferCharacteristics =
    avifTransferCharacteristics(11);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT1361: avifTransferCharacteristics =
    avifTransferCharacteristics(12);
pub const AVIF_TRANSFER_CHARACTERISTICS_SRGB: avifTransferCharacteristics =
    avifTransferCharacteristics(13);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT2020_10BIT: avifTransferCharacteristics =
    avifTransferCharacteristics(14);
pub const AVIF_TRANSFER_CHARACTERISTICS_BT2020_12BIT: avifTransferCharacteristics =
    avifTransferCharacteristics(15);
pub const AVIF_TRANSFER_CHARACTERISTICS_PQ: avifTransferCharacteristics =
    avifTransferCharacteristics(16);
pub const AVIF_TRANSFER_CHARACTERISTICS_SMPTE2084: avifTransferCharacteristics =
    avifTransferCharacteristics(16);
pub const AVIF_TRANSFER_CHARACTERISTICS_SMPTE428: avifTransferCharacteristics =
    avifTransferCharacteristics(17);
pub const AVIF_TRANSFER_CHARACTERISTICS_HLG: avifTransferCharacteristics =
    avifTransferCharacteristics(18);
pub const AVIF_MATRIX_COEFFICIENTS_IDENTITY: avifMatrixCoefficients = avifMatrixCoefficients(0);
pub const AVIF_MATRIX_COEFFICIENTS_BT709: avifMatrixCoefficients = avifMatrixCoefficients(1);
pub const AVIF_MATRIX_COEFFICIENTS_UNSPECIFIED: avifMatrixCoefficients = avifMatrixCoefficients(2);
pub const AVIF_MATRIX_COEFFICIENTS_FCC: avifMatrixCoefficients = avifMatrixCoefficients(4);
pub const AVIF_MATRIX_COEFFICIENTS_BT470BG: avifMatrixCoefficients = avifMatrixCoefficients(5);
pub const AVIF_MATRIX_COEFFICIENTS_BT601: avifMatrixCoefficients = avifMatrixCoefficients(6);
pub const AVIF_MATRIX_COEFFICIENTS_SMPTE240: avifMatrixCoefficients = avifMatrixCoefficients(7);
pub const AVIF_MATRIX_COEFFICIENTS_YCGCO: avifMatrixCoefficients = avifMatrixCoefficients(8);
pub const AVIF_MATRIX_COEFFICIENTS_BT2020_NCL: avifMatrixCoefficients = avifMatrixCoefficients(9);
pub const AVIF_MATRIX_COEFFICIENTS_BT2020_CL: avifMatrixCoefficients = avifMatrixCoefficients(10);
pub const AVIF_MATRIX_COEFFICIENTS_SMPTE2085: avifMatrixCoefficients = avifMatrixCoefficients(11);
pub const AVIF_MATRIX_COEFFICIENTS_CHROMA_DERIVED_NCL: avifMatrixCoefficients =
    avifMatrixCoefficients(12);
pub const AVIF_MATRIX_COEFFICIENTS_CHROMA_DERIVED_CL: avifMatrixCoefficients =
    avifMatrixCoefficients(13);
pub const AVIF_MATRIX_COEFFICIENTS_ICTCP: avifMatrixCoefficients = avifMatrixCoefficients(14);
pub const AVIF_MATRIX_COEFFICIENTS_YCGCO_RE: avifMatrixCoefficients = avifMatrixCoefficients(16);
pub const AVIF_MATRIX_COEFFICIENTS_YCGCO_RO: avifMatrixCoefficients = avifMatrixCoefficients(17);
pub const AVIF_MATRIX_COEFFICIENTS_LAST: avifMatrixCoefficients = avifMatrixCoefficients(18);
impl avifPlanesFlag {
    pub const AVIF_PLANES_YUV: avifPlanesFlag = avifPlanesFlag(1);
    pub const AVIF_PLANES_A: avifPlanesFlag = avifPlanesFlag(2);
    pub const AVIF_PLANES_ALL: avifPlanesFlag = avifPlanesFlag(255);
}
impl avifChannelIndex {
    pub const AVIF_CHAN_Y: avifChannelIndex = avifChannelIndex(0);
    pub const AVIF_CHAN_U: avifChannelIndex = avifChannelIndex(1);
    pub const AVIF_CHAN_V: avifChannelIndex = avifChannelIndex(2);
    pub const AVIF_CHAN_A: avifChannelIndex = avifChannelIndex(3);
}
impl avifResult {
    pub const AVIF_RESULT_OK: avifResult = avifResult(0);
    pub const AVIF_RESULT_UNKNOWN_ERROR: avifResult = avifResult(1);
    pub const AVIF_RESULT_INVALID_FTYP: avifResult = avifResult(2);
    pub const AVIF_RESULT_NO_CONTENT: avifResult = avifResult(3);
    pub const AVIF_RESULT_NO_YUV_FORMAT_SELECTED: avifResult = avifResult(4);
    pub const AVIF_RESULT_REFORMAT_FAILED: avifResult = avifResult(5);
    pub const AVIF_RESULT_UNSUPPORTED_DEPTH: avifResult = avifResult(6);
    pub const AVIF_RESULT_ENCODE_COLOR_FAILED: avifResult = avifResult(7);
    pub const AVIF_RESULT_ENCODE_ALPHA_FAILED: avifResult = avifResult(8);
    pub const AVIF_RESULT_BMFF_PARSE_FAILED: avifResult = avifResult(9);
    pub const AVIF_RESULT_MISSING_IMAGE_ITEM: avifResult = avifResult(10);
    pub const AVIF_RESULT_DECODE_COLOR_FAILED: avifResult = avifResult(11);
    pub const AVIF_RESULT_DECODE_ALPHA_FAILED: avifResult = avifResult(12);
    pub const AVIF_RESULT_COLOR_ALPHA_SIZE_MISMATCH: avifResult = avifResult(13);
    pub const AVIF_RESULT_ISPE_SIZE_MISMATCH: avifResult = avifResult(14);
    pub const AVIF_RESULT_NO_CODEC_AVAILABLE: avifResult = avifResult(15);
    pub const AVIF_RESULT_NO_IMAGES_REMAINING: avifResult = avifResult(16);
    pub const AVIF_RESULT_INVALID_EXIF_PAYLOAD: avifResult = avifResult(17);
    pub const AVIF_RESULT_INVALID_IMAGE_GRID: avifResult = avifResult(18);
    pub const AVIF_RESULT_INVALID_CODEC_SPECIFIC_OPTION: avifResult = avifResult(19);
    pub const AVIF_RESULT_TRUNCATED_DATA: avifResult = avifResult(20);
    pub const AVIF_RESULT_IO_NOT_SET: avifResult = avifResult(21);
    pub const AVIF_RESULT_IO_ERROR: avifResult = avifResult(22);
    pub const AVIF_RESULT_WAITING_ON_IO: avifResult = avifResult(23);
    pub const AVIF_RESULT_INVALID_ARGUMENT: avifResult = avifResult(24);
    pub const AVIF_RESULT_NOT_IMPLEMENTED: avifResult = avifResult(25);
    pub const AVIF_RESULT_OUT_OF_MEMORY: avifResult = avifResult(26);
    pub const AVIF_RESULT_CANNOT_CHANGE_SETTING: avifResult = avifResult(27);
    pub const AVIF_RESULT_INCOMPATIBLE_IMAGE: avifResult = avifResult(28);
    pub const AVIF_RESULT_INTERNAL_ERROR: avifResult = avifResult(29);
    pub const AVIF_RESULT_ENCODE_GAIN_MAP_FAILED: avifResult = avifResult(30);
    pub const AVIF_RESULT_DECODE_GAIN_MAP_FAILED: avifResult = avifResult(31);
    pub const AVIF_RESULT_INVALID_TONE_MAPPED_IMAGE: avifResult = avifResult(32);
    pub const AVIF_RESULT_ENCODE_SAMPLE_TRANSFORM_FAILED: avifResult = avifResult(33);
    pub const AVIF_RESULT_DECODE_SAMPLE_TRANSFORM_FAILED: avifResult = avifResult(34);
    pub const AVIF_RESULT_NO_AV1_ITEMS_FOUND: avifResult = avifResult(10);
}
impl avifHeaderFormat {
    pub const AVIF_HEADER_DEFAULT: avifHeaderFormat = avifHeaderFormat(0);
    pub const AVIF_HEADER_FULL: avifHeaderFormat = avifHeaderFormat(0);
}
impl avifPixelFormat {
    pub const AVIF_PIXEL_FORMAT_NONE: avifPixelFormat = avifPixelFormat(0);
    pub const AVIF_PIXEL_FORMAT_YUV444: avifPixelFormat = avifPixelFormat(1);
    pub const AVIF_PIXEL_FORMAT_YUV422: avifPixelFormat = avifPixelFormat(2);
    pub const AVIF_PIXEL_FORMAT_YUV420: avifPixelFormat = avifPixelFormat(3);
    pub const AVIF_PIXEL_FORMAT_YUV400: avifPixelFormat = avifPixelFormat(4);
    pub const AVIF_PIXEL_FORMAT_COUNT: avifPixelFormat = avifPixelFormat(5);
}
impl avifChromaSamplePosition {
    pub const AVIF_CHROMA_SAMPLE_POSITION_UNKNOWN: avifChromaSamplePosition =
        avifChromaSamplePosition(0);
    pub const AVIF_CHROMA_SAMPLE_POSITION_VERTICAL: avifChromaSamplePosition =
        avifChromaSamplePosition(1);
    pub const AVIF_CHROMA_SAMPLE_POSITION_COLOCATED: avifChromaSamplePosition =
        avifChromaSamplePosition(2);
    pub const AVIF_CHROMA_SAMPLE_POSITION_RESERVED: avifChromaSamplePosition =
        avifChromaSamplePosition(3);
}
impl avifRange {
    #[doc = "<- Y  [16..235],  UV  [16..240]  (bit depth 8) */\n/**<- Y  [64..940],  UV  [64..960]  (bit depth 10) */\n/**<- Y [256..3760], UV [256..3840] (bit depth 12)"]
    pub const AVIF_RANGE_LIMITED: avifRange = avifRange(0);
    #[doc = "<- [0..255]  (bit depth 8) */\n/**<- [0..1023] (bit depth 10) */\n/**<- [0..4095] (bit depth 12)"]
    pub const AVIF_RANGE_FULL: avifRange = avifRange(1);
}
impl avifTransformFlag {
    pub const AVIF_TRANSFORM_NONE: avifTransformFlag = avifTransformFlag(0);
    pub const AVIF_TRANSFORM_PASP: avifTransformFlag = avifTransformFlag(1);
    pub const AVIF_TRANSFORM_CLAP: avifTransformFlag = avifTransformFlag(2);
    pub const AVIF_TRANSFORM_IROT: avifTransformFlag = avifTransformFlag(4);
    pub const AVIF_TRANSFORM_IMIR: avifTransformFlag = avifTransformFlag(8);
}
impl avifSampleTransformRecipe {
    pub const AVIF_SAMPLE_TRANSFORM_NONE: avifSampleTransformRecipe = avifSampleTransformRecipe(0);
    pub const AVIF_SAMPLE_TRANSFORM_BIT_DEPTH_EXTENSION_8B_8B: avifSampleTransformRecipe =
        avifSampleTransformRecipe(1);
    pub const AVIF_SAMPLE_TRANSFORM_BIT_DEPTH_EXTENSION_12B_4B: avifSampleTransformRecipe =
        avifSampleTransformRecipe(2);
    pub const AVIF_SAMPLE_TRANSFORM_BIT_DEPTH_EXTENSION_12B_8B_OVERLAP_4B:
        avifSampleTransformRecipe = avifSampleTransformRecipe(3);
}
impl avifRGBFormat {
    pub const AVIF_RGB_FORMAT_RGB: avifRGBFormat = avifRGBFormat(0);
    pub const AVIF_RGB_FORMAT_RGBA: avifRGBFormat = avifRGBFormat(1);
    pub const AVIF_RGB_FORMAT_ARGB: avifRGBFormat = avifRGBFormat(2);
    pub const AVIF_RGB_FORMAT_BGR: avifRGBFormat = avifRGBFormat(3);
    pub const AVIF_RGB_FORMAT_BGRA: avifRGBFormat = avifRGBFormat(4);
    pub const AVIF_RGB_FORMAT_ABGR: avifRGBFormat = avifRGBFormat(5);
    pub const AVIF_RGB_FORMAT_RGB_565: avifRGBFormat = avifRGBFormat(6);
    pub const AVIF_RGB_FORMAT_GRAY: avifRGBFormat = avifRGBFormat(7);
    pub const AVIF_RGB_FORMAT_GRAYA: avifRGBFormat = avifRGBFormat(8);
    pub const AVIF_RGB_FORMAT_AGRAY: avifRGBFormat = avifRGBFormat(9);
    pub const AVIF_RGB_FORMAT_COUNT: avifRGBFormat = avifRGBFormat(10);
}
impl avifChromaUpsampling {
    pub const AVIF_CHROMA_UPSAMPLING_AUTOMATIC: avifChromaUpsampling = avifChromaUpsampling(0);
    pub const AVIF_CHROMA_UPSAMPLING_FASTEST: avifChromaUpsampling = avifChromaUpsampling(1);
    pub const AVIF_CHROMA_UPSAMPLING_BEST_QUALITY: avifChromaUpsampling = avifChromaUpsampling(2);
    pub const AVIF_CHROMA_UPSAMPLING_NEAREST: avifChromaUpsampling = avifChromaUpsampling(3);
    pub const AVIF_CHROMA_UPSAMPLING_BILINEAR: avifChromaUpsampling = avifChromaUpsampling(4);
}
impl avifChromaDownsampling {
    pub const AVIF_CHROMA_DOWNSAMPLING_AUTOMATIC: avifChromaDownsampling =
        avifChromaDownsampling(0);
    pub const AVIF_CHROMA_DOWNSAMPLING_FASTEST: avifChromaDownsampling = avifChromaDownsampling(1);
    pub const AVIF_CHROMA_DOWNSAMPLING_BEST_QUALITY: avifChromaDownsampling =
        avifChromaDownsampling(2);
    pub const AVIF_CHROMA_DOWNSAMPLING_AVERAGE: avifChromaDownsampling = avifChromaDownsampling(3);
    pub const AVIF_CHROMA_DOWNSAMPLING_SHARP_YUV: avifChromaDownsampling =
        avifChromaDownsampling(4);
}
impl avifCodecChoice {
    pub const AVIF_CODEC_CHOICE_AUTO: avifCodecChoice = avifCodecChoice(0);
    pub const AVIF_CODEC_CHOICE_AOM: avifCodecChoice = avifCodecChoice(1);
    pub const AVIF_CODEC_CHOICE_DAV1D: avifCodecChoice = avifCodecChoice(2);
    pub const AVIF_CODEC_CHOICE_LIBGAV1: avifCodecChoice = avifCodecChoice(3);
    pub const AVIF_CODEC_CHOICE_RAV1E: avifCodecChoice = avifCodecChoice(4);
    pub const AVIF_CODEC_CHOICE_SVT: avifCodecChoice = avifCodecChoice(5);
    pub const AVIF_CODEC_CHOICE_AVM: avifCodecChoice = avifCodecChoice(6);
}
impl avifCodecFlag {
    pub const AVIF_CODEC_FLAG_CAN_DECODE: avifCodecFlag = avifCodecFlag(1);
    pub const AVIF_CODEC_FLAG_CAN_ENCODE: avifCodecFlag = avifCodecFlag(2);
}
impl avifStrictFlag {
    pub const AVIF_STRICT_DISABLED: avifStrictFlag = avifStrictFlag(0);
    pub const AVIF_STRICT_PIXI_REQUIRED: avifStrictFlag = avifStrictFlag(1);
    pub const AVIF_STRICT_CLAP_VALID: avifStrictFlag = avifStrictFlag(2);
    pub const AVIF_STRICT_ALPHA_ISPE_REQUIRED: avifStrictFlag = avifStrictFlag(4);
    pub const AVIF_STRICT_ENABLED: avifStrictFlag = avifStrictFlag(7);
}
impl avifDecoderSource {
    pub const AVIF_DECODER_SOURCE_AUTO: avifDecoderSource = avifDecoderSource(0);
    pub const AVIF_DECODER_SOURCE_PRIMARY_ITEM: avifDecoderSource = avifDecoderSource(1);
    pub const AVIF_DECODER_SOURCE_TRACKS: avifDecoderSource = avifDecoderSource(2);
}
impl avifProgressiveState {
    pub const AVIF_PROGRESSIVE_STATE_UNAVAILABLE: avifProgressiveState = avifProgressiveState(0);
    pub const AVIF_PROGRESSIVE_STATE_AVAILABLE: avifProgressiveState = avifProgressiveState(1);
    pub const AVIF_PROGRESSIVE_STATE_ACTIVE: avifProgressiveState = avifProgressiveState(2);
}
impl avifImageContentTypeFlag {
    pub const AVIF_IMAGE_CONTENT_NONE: avifImageContentTypeFlag = avifImageContentTypeFlag(0);
    pub const AVIF_IMAGE_CONTENT_COLOR_AND_ALPHA: avifImageContentTypeFlag =
        avifImageContentTypeFlag(3);
    pub const AVIF_IMAGE_CONTENT_GAIN_MAP: avifImageContentTypeFlag = avifImageContentTypeFlag(4);
    pub const AVIF_IMAGE_CONTENT_ALL: avifImageContentTypeFlag = avifImageContentTypeFlag(7);
    pub const AVIF_IMAGE_CONTENT_SAMPLE_TRANSFORMS: avifImageContentTypeFlag =
        avifImageContentTypeFlag(8);
    pub const AVIF_IMAGE_CONTENT_DECODE_DEFAULT: avifImageContentTypeFlag =
        avifImageContentTypeFlag(3);
}
impl avifAddImageFlag {
    pub const AVIF_ADD_IMAGE_FLAG_NONE: avifAddImageFlag = avifAddImageFlag(0);
    pub const AVIF_ADD_IMAGE_FLAG_FORCE_KEYFRAME: avifAddImageFlag = avifAddImageFlag(1);
    pub const AVIF_ADD_IMAGE_FLAG_SINGLE: avifAddImageFlag = avifAddImageFlag(2);
}
unsafe extern "C" {
    pub fn avifVersion() -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifCodecVersions(outBuffer: *mut ::core::ffi::c_char);
}
unsafe extern "C" {
    pub fn avifLibYUVVersion() -> ::core::ffi::c_uint;
}
unsafe extern "C" {
    pub fn avifAlloc(size: usize) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn avifFree(p: *mut ::core::ffi::c_void);
}
unsafe extern "C" {
    pub fn avifResultToString(result: avifResult) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifRWDataRealloc(raw: *mut avifRWData, newSize: usize) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRWDataSet(raw: *mut avifRWData, data: *const u8, len: usize) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRWDataFree(raw: *mut avifRWData);
}
unsafe extern "C" {
    pub fn avifGetExifTiffHeaderOffset(
        exif: *const u8,
        exifSize: usize,
        offset: *mut usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifGetExifOrientationOffset(
        exif: *const u8,
        exifSize: usize,
        offset: *mut usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifPixelFormatToString(format: avifPixelFormat) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifGetPixelFormatInfo(format: avifPixelFormat, info: *mut avifPixelFormatInfo);
}
unsafe extern "C" {
    pub fn avifColorPrimariesGetValues(acp: avifColorPrimaries, outPrimaries: *mut f32);
}
unsafe extern "C" {
    pub fn avifColorPrimariesFind(
        inPrimaries: *const f32,
        outName: *mut *const ::core::ffi::c_char,
    ) -> avifColorPrimaries;
}
unsafe extern "C" {
    pub fn avifTransferCharacteristicsGetGamma(
        atc: avifTransferCharacteristics,
        gamma: *mut f32,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifTransferCharacteristicsFindByGamma(gamma: f32) -> avifTransferCharacteristics;
}
unsafe extern "C" {
    pub fn avifDiagnosticsClearError(diag: *mut avifDiagnostics);
}
unsafe extern "C" {
    pub fn avifDoubleToSignedFraction(v: f64, fraction: *mut avifSignedFraction) -> avifBool;
}
unsafe extern "C" {
    pub fn avifDoubleToUnsignedFraction(v: f64, fraction: *mut avifUnsignedFraction) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCropRectFromCleanApertureBox(
        cropRect: *mut avifCropRect,
        clap: *const avifCleanApertureBox,
        imageW: u32,
        imageH: u32,
        diag: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCleanApertureBoxFromCropRect(
        clap: *mut avifCleanApertureBox,
        cropRect: *const avifCropRect,
        imageW: u32,
        imageH: u32,
        diag: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCropRectRequiresUpsampling(
        cropRect: *const avifCropRect,
        yuvFormat: avifPixelFormat,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCropRectConvertCleanApertureBox(
        arg1: *mut avifCropRect,
        arg2: *const avifCleanApertureBox,
        arg3: u32,
        arg4: u32,
        arg5: avifPixelFormat,
        arg6: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifCleanApertureBoxConvertCropRect(
        arg1: *mut avifCleanApertureBox,
        arg2: *const avifCropRect,
        arg3: u32,
        arg4: u32,
        arg5: avifPixelFormat,
        arg6: *mut avifDiagnostics,
    ) -> avifBool;
}
unsafe extern "C" {
    pub fn avifGainMapCreate() -> *mut avifGainMap;
}
unsafe extern "C" {
    pub fn avifGainMapDestroy(gainMap: *mut avifGainMap);
}
unsafe extern "C" {
    pub fn avifImageCreate(
        width: u32,
        height: u32,
        depth: u32,
        yuvFormat: avifPixelFormat,
    ) -> *mut avifImage;
}
unsafe extern "C" {
    pub fn avifImageCreateEmpty() -> *mut avifImage;
}
unsafe extern "C" {
    pub fn avifImageCopy(
        dstImage: *mut avifImage,
        srcImage: *const avifImage,
        planes: avifPlanesFlags,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageSetViewRect(
        dstImage: *mut avifImage,
        srcImage: *const avifImage,
        rect: *const avifCropRect,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageDestroy(image: *mut avifImage);
}
unsafe extern "C" {
    pub fn avifImageSetProfileICC(
        image: *mut avifImage,
        icc: *const u8,
        iccSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageSetMetadataExif(
        image: *mut avifImage,
        exif: *const u8,
        exifSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageSetMetadataXMP(
        image: *mut avifImage,
        xmp: *const u8,
        xmpSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageAllocatePlanes(image: *mut avifImage, planes: avifPlanesFlags) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageFreePlanes(image: *mut avifImage, planes: avifPlanesFlags);
}
unsafe extern "C" {
    pub fn avifImageStealPlanes(
        dstImage: *mut avifImage,
        srcImage: *mut avifImage,
        planes: avifPlanesFlags,
    );
}
unsafe extern "C" {
    pub fn avifImageAddOpaqueProperty(
        image: *mut avifImage,
        boxtype: *const u8,
        data: *const u8,
        dataSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageAddUUIDProperty(
        image: *mut avifImage,
        uuid: *const u8,
        data: *const u8,
        dataSize: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageScale(
        image: *mut avifImage,
        dstWidth: u32,
        dstHeight: u32,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBFormatChannelCount(format: avifRGBFormat) -> u32;
}
unsafe extern "C" {
    pub fn avifRGBFormatHasAlpha(format: avifRGBFormat) -> avifBool;
}
unsafe extern "C" {
    pub fn avifRGBFormatIsGray(format: avifRGBFormat) -> avifBool;
}
unsafe extern "C" {
    pub fn avifRGBImageSetDefaults(rgb: *mut avifRGBImage, image: *const avifImage);
}
unsafe extern "C" {
    pub fn avifRGBImagePixelSize(rgb: *const avifRGBImage) -> u32;
}
unsafe extern "C" {
    pub fn avifRGBImageAllocatePixels(rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageFreePixels(rgb: *mut avifRGBImage);
}
unsafe extern "C" {
    pub fn avifImageRGBToYUV(image: *mut avifImage, rgb: *const avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageYUVToRGB(image: *const avifImage, rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImagePremultiplyAlpha(rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageUnpremultiplyAlpha(rgb: *mut avifRGBImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifFullToLimitedY(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifFullToLimitedUV(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifLimitedToFullY(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifLimitedToFullUV(depth: u32, v: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn avifCodecName(
        choice: avifCodecChoice,
        requiredFlags: avifCodecFlags,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifCodecChoiceFromName(name: *const ::core::ffi::c_char) -> avifCodecChoice;
}
unsafe extern "C" {
    pub fn avifIOCreateMemoryReader(data: *const u8, size: usize) -> *mut avifIO;
}
unsafe extern "C" {
    pub fn avifIOCreateFileReader(filename: *const ::core::ffi::c_char) -> *mut avifIO;
}
unsafe extern "C" {
    pub fn avifIODestroy(io: *mut avifIO);
}
unsafe extern "C" {
    pub fn avifProgressiveStateToString(
        progressiveState: avifProgressiveState,
    ) -> *const ::core::ffi::c_char;
}
unsafe extern "C" {
    pub fn avifDecoderCreate() -> *mut avifDecoder;
}
unsafe extern "C" {
    pub fn avifDecoderDestroy(decoder: *mut avifDecoder);
}
unsafe extern "C" {
    pub fn avifDecoderRead(decoder: *mut avifDecoder, image: *mut avifImage) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderReadMemory(
        decoder: *mut avifDecoder,
        image: *mut avifImage,
        data: *const u8,
        size: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderReadFile(
        decoder: *mut avifDecoder,
        image: *mut avifImage,
        filename: *const ::core::ffi::c_char,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderSetSource(decoder: *mut avifDecoder, source: avifDecoderSource)
    -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderSetIO(decoder: *mut avifDecoder, io: *mut avifIO);
}
unsafe extern "C" {
    pub fn avifDecoderSetIOMemory(
        decoder: *mut avifDecoder,
        data: *const u8,
        size: usize,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderSetIOFile(
        decoder: *mut avifDecoder,
        filename: *const ::core::ffi::c_char,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderParse(decoder: *mut avifDecoder) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderNextImage(decoder: *mut avifDecoder) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderNthImage(decoder: *mut avifDecoder, frameIndex: u32) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderReset(decoder: *mut avifDecoder) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderIsKeyframe(decoder: *const avifDecoder, frameIndex: u32) -> avifBool;
}
unsafe extern "C" {
    pub fn avifDecoderNearestKeyframe(decoder: *const avifDecoder, frameIndex: u32) -> u32;
}
unsafe extern "C" {
    pub fn avifDecoderNthImageTiming(
        decoder: *const avifDecoder,
        frameIndex: u32,
        outTiming: *mut avifImageTiming,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifDecoderDecodedRowCount(decoder: *const avifDecoder) -> u32;
}
unsafe extern "C" {
    pub fn avifDecoderNthImageMaxExtent(
        decoder: *const avifDecoder,
        frameIndex: u32,
        outExtent: *mut avifExtent,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderCreate() -> *mut avifEncoder;
}
unsafe extern "C" {
    pub fn avifEncoderWrite(
        encoder: *mut avifEncoder,
        image: *const avifImage,
        output: *mut avifRWData,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderDestroy(encoder: *mut avifEncoder);
}
unsafe extern "C" {
    pub fn avifEncoderAddImage(
        encoder: *mut avifEncoder,
        image: *const avifImage,
        durationInTimescales: u64,
        addImageFlags: avifAddImageFlags,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderAddImageGrid(
        encoder: *mut avifEncoder,
        gridCols: u32,
        gridRows: u32,
        cellImages: *const *const avifImage,
        addImageFlags: avifAddImageFlags,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderFinish(encoder: *mut avifEncoder, output: *mut avifRWData) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderSetCodecSpecificOption(
        encoder: *mut avifEncoder,
        key: *const ::core::ffi::c_char,
        value: *const ::core::ffi::c_char,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifEncoderGetGainMapSizeBytes(encoder: *mut avifEncoder) -> usize;
}
unsafe extern "C" {
    pub fn avifImageUsesU16(image: *const avifImage) -> avifBool;
}
unsafe extern "C" {
    pub fn avifImageIsOpaque(image: *const avifImage) -> avifBool;
}
unsafe extern "C" {
    pub fn avifImagePlane(image: *const avifImage, channel: ::core::ffi::c_int) -> *mut u8;
}
unsafe extern "C" {
    pub fn avifImagePlaneRowBytes(image: *const avifImage, channel: ::core::ffi::c_int) -> u32;
}
unsafe extern "C" {
    pub fn avifImagePlaneWidth(image: *const avifImage, channel: ::core::ffi::c_int) -> u32;
}
unsafe extern "C" {
    pub fn avifImagePlaneHeight(image: *const avifImage, channel: ::core::ffi::c_int) -> u32;
}
unsafe extern "C" {
    pub fn avifPeekCompatibleFileType(input: *const avifROData) -> avifBool;
}
unsafe extern "C" {
    pub fn avifImageApplyGainMap(
        baseImage: *const avifImage,
        gainMap: *const avifGainMap,
        hdrHeadroom: f32,
        outputColorPrimaries: avifColorPrimaries,
        outputTransferCharacteristics: avifTransferCharacteristics,
        toneMappedImage: *mut avifRGBImage,
        clli: *mut avifContentLightLevelInformationBox,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageApplyGainMap(
        baseImage: *const avifRGBImage,
        baseColorPrimaries: avifColorPrimaries,
        baseTransferCharacteristics: avifTransferCharacteristics,
        gainMap: *const avifGainMap,
        hdrHeadroom: f32,
        outputColorPrimaries: avifColorPrimaries,
        outputTransferCharacteristics: avifTransferCharacteristics,
        toneMappedImage: *mut avifRGBImage,
        clli: *mut avifContentLightLevelInformationBox,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifRGBImageComputeGainMap(
        baseRgbImage: *const avifRGBImage,
        baseColorPrimaries: avifColorPrimaries,
        baseTransferCharacteristics: avifTransferCharacteristics,
        altRgbImage: *const avifRGBImage,
        altColorPrimaries: avifColorPrimaries,
        altTransferCharacteristics: avifTransferCharacteristics,
        gainMap: *mut avifGainMap,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
unsafe extern "C" {
    pub fn avifImageComputeGainMap(
        baseImage: *const avifImage,
        altImage: *const avifImage,
        gainMap: *mut avifGainMap,
        diag: *mut avifDiagnostics,
    ) -> avifResult;
}
